// Generated from context-sensitive PokeAPI encounter records on 2026-08-22.
// These records preserve hunting categories that cannot be inferred from the species alone.

export const GENERATED_CONTEXT_ENCOUNTER_TUPLES = [
  [21,"sun","gen7-fishing",["Alola Route 3 — North"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [21,"moon","gen7-fishing",["Alola Route 3 — North"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [21,"ultrasun","gen7-fishing",["Alola Route 3 — North"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [21,"ultramoon","gen7-fishing",["Alola Route 3 — North"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [22,"sun","gen7-fishing",["Alola Route 10","Poni Plains — North"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [22,"moon","gen7-fishing",["Alola Route 10","Poni Plains — North"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [22,"ultrasun","gen7-fishing",["Alola Route 10","Poni Plains — North"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [22,"ultramoon","gen7-fishing",["Alola Route 10","Poni Plains — North"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [23,"gold","gen2-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [23,"heartgold","gen4-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [23,"ultrasun","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [23,"ultramoon","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [25,"crystal","gen2-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [27,"silver","gen2-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [27,"soulsilver","gen4-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [35,"firered","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [35,"leafgreen","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [57,"sun","gen7-fishing",["Poni Plains — West"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [57,"moon","gen7-fishing",["Poni Plains — West"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [57,"ultrasun","gen7-fishing",["Poni Plains — West"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [57,"ultramoon","gen7-fishing",["Poni Plains — West"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [63,"gold","gen2-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [63,"silver","gen2-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [63,"crystal","gen2-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [63,"firered","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [63,"leafgreen","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [63,"heartgold","gen4-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [63,"soulsilver","gen4-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [72,"sun","gen7-fishing",["Hano Beach"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [72,"moon","gen7-fishing",["Hano Beach"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [72,"ultrasun","gen7-fishing",["Hano Beach"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [72,"ultramoon","gen7-fishing",["Hano Beach"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [90,"sun","gen7-fishing",["Kalae Bay"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [90,"moon","gen7-fishing",["Kalae Bay"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [90,"ultrasun","gen7-fishing",["Kalae Bay"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [90,"ultramoon","gen7-fishing",["Kalae Bay"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [96,"ultrasun","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [96,"ultramoon","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [104,"crystal","gen2-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [113,"ultrasun","gen7-fishing",["Poni Plains — Center"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [113,"ultramoon","gen7-fishing",["Poni Plains — Center"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [118,"sun","gen7-fishing",["Brooklet Hill — North","Brooklet Hill — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [118,"moon","gen7-fishing",["Brooklet Hill — North","Brooklet Hill — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [118,"ultrasun","gen7-fishing",["Brooklet Hill — North","Brooklet Hill — South","Malie Garden"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [118,"ultramoon","gen7-fishing",["Brooklet Hill — North","Brooklet Hill — South","Malie Garden"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [120,"ultrasun","gen7-fishing",["Alola Route 7"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [120,"ultramoon","gen7-fishing",["Alola Route 7"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [122,"gold","gen2-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [122,"silver","gen2-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [122,"heartgold","gen4-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [122,"soulsilver","gen4-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [123,"firered","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [123,"sun","gen7-fishing",["Poni Plains — Center"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [123,"moon","gen7-fishing",["Poni Plains — Center"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [123,"ultrasun","gen7-fishing",["Poni Plains — Center"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [123,"ultramoon","gen7-fishing",["Poni Plains — Center"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [127,"leafgreen","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [129,"sun","gen7-fishing",["Alola Route 14","Alola Route 15 — Main","Alola Route 8 — Main","Brooklet Hill — North","Brooklet Hill — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [129,"moon","gen7-fishing",["Alola Route 14","Alola Route 15 — Main","Alola Route 8 — Main","Brooklet Hill — North","Brooklet Hill — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [129,"ultrasun","gen7-fishing",["Akala Outskirts","Alola Route 14","Alola Route 15 — Main","Alola Route 7","Alola Route 8 — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [129,"ultramoon","gen7-fishing",["Akala Outskirts","Alola Route 14","Alola Route 15 — Main","Alola Route 7","Alola Route 8 — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [130,"ultrasun","gen7-fishing",["Malie Garden"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [130,"ultramoon","gen7-fishing",["Malie Garden"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [133,"gold","gen2-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [133,"silver","gen2-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [133,"heartgold","gen4-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [133,"soulsilver","gen4-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [137,"gold","gen2-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [137,"silver","gen2-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [137,"crystal","gen2-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [137,"firered","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [137,"leafgreen","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [137,"heartgold","gen4-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [137,"soulsilver","gen4-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [147,"gold","gen2-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [147,"silver","gen2-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [147,"firered","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [147,"leafgreen","gen3-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [147,"heartgold","gen4-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [147,"soulsilver","gen4-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [147,"sun","gen7-fishing",["Poni Gauntlet","Poni Meadow","Vast Poni Canyon — Northwest"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [147,"moon","gen7-fishing",["Poni Gauntlet","Poni Meadow","Vast Poni Canyon — Northwest"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [147,"ultrasun","gen7-fishing",["Poni Gauntlet","Poni Meadow"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [147,"ultramoon","gen7-fishing",["Poni Gauntlet","Poni Meadow"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [170,"sun","gen7-fishing",["Alola Route 8 — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [170,"moon","gen7-fishing",["Alola Route 8 — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [170,"ultrasun","gen7-fishing",["Akala Outskirts","Alola Route 8 — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [170,"ultramoon","gen7-fishing",["Akala Outskirts","Alola Route 8 — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [190,"ultrasun","gen7-fishing",["Poni Plains — West"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [190,"ultramoon","gen7-fishing",["Poni Plains — West"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [202,"crystal","gen2-game-corner",["Goldenrod City — Game Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [204,"ultrasun","gen7-fishing",["Alola Route 10"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [204,"ultramoon","gen7-fishing",["Alola Route 10"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [206,"ultrasun","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [206,"ultramoon","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [222,"sun","gen7-fishing",["Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [222,"moon","gen7-fishing",["Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [222,"ultrasun","gen7-fishing",["Hauoli City — Beachfront","Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [222,"ultramoon","gen7-fishing",["Hauoli City — Beachfront","Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [223,"ultrasun","gen7-fishing",["Alola Route 8 — Main","Hauoli City — Beachfront","Kalae Bay","Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [223,"ultramoon","gen7-fishing",["Alola Route 8 — Main","Hauoli City — Beachfront","Kalae Bay","Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [227,"sun","gen7-fishing",["Alola Route 10"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [227,"moon","gen7-fishing",["Alola Route 10"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [227,"ultrasun","gen7-fishing",["Alola Route 10"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [227,"ultramoon","gen7-fishing",["Alola Route 10"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [246,"crystal","gen2-game-corner",["Celadon City — Prize Corner"],["Save before redeeming the prize Pokémon and check each generated prize."],[]],
  [296,"sun","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [296,"moon","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [296,"ultrasun","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [296,"ultramoon","gen7-fishing",["Alola Route 2 — North","Alola Route 2 — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [297,"sun","gen7-fishing",["Poni Plains — Center"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [297,"moon","gen7-fishing",["Poni Plains — Center"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [318,"ultrasun","gen7-fishing",["Ancient Poni Path","Poni Breaker Coast"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [318,"ultramoon","gen7-fishing",["Ancient Poni Path","Poni Breaker Coast"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [319,"sun","gen7-fishing",["Poni Breaker Coast"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [319,"moon","gen7-fishing",["Poni Breaker Coast"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [320,"sun","gen7-fishing",["Poni Breaker Coast","Poni Wilds","Seafolk Village — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [320,"moon","gen7-fishing",["Poni Breaker Coast","Poni Wilds","Seafolk Village — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [320,"ultrasun","gen7-fishing",["Ancient Poni Path","Poni Breaker Coast","Seafolk Village — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [320,"ultramoon","gen7-fishing",["Ancient Poni Path","Poni Breaker Coast","Seafolk Village — Main"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [321,"sun","gen7-fishing",["Poni Wilds"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [321,"moon","gen7-fishing",["Poni Wilds"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [321,"ultrasun","gen7-fishing",["Poni Breaker Coast"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [321,"ultramoon","gen7-fishing",["Poni Breaker Coast"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [328,"sun","gen7-fishing",["Haina Desert"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [328,"moon","gen7-fishing",["Haina Desert"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [328,"ultrasun","gen7-fishing",["Haina Desert"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [328,"ultramoon","gen7-fishing",["Haina Desert"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [339,"sun","gen7-fishing",["Paniola Town","Poni Gauntlet","Poni Meadow","Seaward Cave","Vast Poni Canyon — Northwest"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [339,"moon","gen7-fishing",["Paniola Town","Poni Gauntlet","Poni Meadow","Seaward Cave","Vast Poni Canyon — Northwest"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [339,"ultrasun","gen7-fishing",["Paniola Town","Poni Gauntlet","Poni Meadow","Seaward Cave","Vast Poni Canyon — Northwest"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [339,"ultramoon","gen7-fishing",["Paniola Town","Poni Gauntlet","Poni Meadow","Seaward Cave","Vast Poni Canyon — Northwest"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [341,"ultrasun","gen7-fishing",["Vast Poni Canyon — Northwest"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [341,"ultramoon","gen7-fishing",["Vast Poni Canyon — Northwest"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [349,"sun","gen7-fishing",["Brooklet Hill — North","Brooklet Hill — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [349,"moon","gen7-fishing",["Brooklet Hill — North","Brooklet Hill — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [349,"ultrasun","gen7-fishing",["Brooklet Hill — North","Brooklet Hill — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [349,"ultramoon","gen7-fishing",["Brooklet Hill — North","Brooklet Hill — South"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [352,"ultrasun","gen7-fishing",["Dividing Peak Tunnel"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [352,"ultramoon","gen7-fishing",["Dividing Peak Tunnel"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [366,"ultrasun","gen7-fishing",["Alola Route 15 — Main","Hauoli City — Beachfront","Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [366,"ultramoon","gen7-fishing",["Alola Route 15 — Main","Hauoli City — Beachfront","Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [369,"sun","gen7-fishing",["Poni Wilds"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [369,"moon","gen7-fishing",["Poni Wilds"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [369,"ultrasun","gen7-fishing",["Ancient Poni Path","Poni Breaker Coast"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [369,"ultramoon","gen7-fishing",["Ancient Poni Path","Poni Breaker Coast"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [370,"sun","gen7-fishing",["Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [370,"moon","gen7-fishing",["Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [370,"ultrasun","gen7-fishing",["Hauoli City — Beachfront","Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
  [370,"ultramoon","gen7-fishing",["Hauoli City — Beachfront","Melemele Sea"],["Fish at the bubbling fishing spot; leaving and returning refreshes the spot."],[]],
] as const;
