export const GENERATED_GEN5_ENCOUNTER_TUPLES = [
  [495, 'black', 'gen5-soft-reset', ["Nuvema Town Area"], [], []],
  [495, 'black2', 'gen5-soft-reset', ["Aspertia City Area"], [], []],
  [495, 'white', 'gen5-soft-reset', ["Nuvema Town Area"], [], []],
  [495, 'white2', 'gen5-soft-reset', ["Aspertia City Area"], [], []],
  [498, 'black', 'gen5-soft-reset', ["Nuvema Town Area"], [], []],
  [498, 'black2', 'gen5-soft-reset', ["Aspertia City Area"], [], []],
  [498, 'white', 'gen5-soft-reset', ["Nuvema Town Area"], [], []],
  [498, 'white2', 'gen5-soft-reset', ["Aspertia City Area"], [], []],
  [501, 'black', 'gen5-soft-reset', ["Nuvema Town Area"], [], []],
  [501, 'black2', 'gen5-soft-reset', ["Aspertia City Area"], [], []],
  [501, 'white', 'gen5-soft-reset', ["Nuvema Town Area"], [], []],
  [501, 'white2', 'gen5-soft-reset', ["Aspertia City Area"], [], []],
  [504, 'black', 'gen5-double-encounter', ["Unova Route 3 Area"], [], []],
  [504, 'black', 'gen5-random', ["Dreamyard Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [504, 'black2', 'gen5-double-encounter', ["Virbank Complex Inner","Unova Route 20 Area"], [], []],
  [504, 'black2', 'gen5-random', ["Floccesy Ranch Inner","Virbank Complex Outer","Virbank Complex Inner","Unova Route 19 Area","Unova Route 20 Area"], [], []],
  [504, 'black2', 'gen5-rustling-grass', ["Unova Route 19 Area"], [], []],
  [504, 'white', 'gen5-double-encounter', ["Unova Route 3 Area"], [], []],
  [504, 'white', 'gen5-random', ["Dreamyard Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [504, 'white2', 'gen5-double-encounter', ["Virbank Complex Inner","Unova Route 20 Area"], [], []],
  [504, 'white2', 'gen5-random', ["Floccesy Ranch Inner","Virbank Complex Outer","Virbank Complex Inner","Unova Route 19 Area","Unova Route 20 Area"], [], []],
  [504, 'white2', 'gen5-rustling-grass', ["Unova Route 19 Area"], [], []],
  [505, 'black', 'gen5-double-encounter', ["Dreamyard Area","Unova Route 1 Area","Unova Route 7 Area","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [505, 'black', 'gen5-random', ["P2 Laboratory Area","Unova Route 7 Area","Unova Route 18 Area"], [], []],
  [505, 'black2', 'gen5-double-encounter', ["Dreamyard Area","Dreamyard B1f","Unova Route 1 Area","Unova Route 3 Area","Unova Route 7 Area","Unova Route 18 Area"], [], []],
  [505, 'black2', 'gen5-random', ["Dreamyard Area","P2 Laboratory Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area","Unova Route 7 Area","Unova Route 18 Area"], [], []],
  [505, 'white', 'gen5-double-encounter', ["Dreamyard Area","Unova Route 1 Area","Unova Route 7 Area","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [505, 'white', 'gen5-random', ["P2 Laboratory Area","Unova Route 7 Area","Unova Route 18 Area"], [], []],
  [505, 'white2', 'gen5-double-encounter', ["Dreamyard Area","Dreamyard B1f","Unova Route 1 Area","Unova Route 3 Area","Unova Route 7 Area","Unova Route 18 Area"], [], []],
  [505, 'white2', 'gen5-random', ["Dreamyard Area","P2 Laboratory Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area","Unova Route 7 Area","Unova Route 18 Area"], [], []],
  [506, 'black', 'gen5-double-encounter', ["Unova Route 3 Area"], [], []],
  [506, 'black', 'gen5-random', ["Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [506, 'black2', 'gen5-random', ["Floccesy Ranch Inner"], [], []],
  [506, 'white', 'gen5-double-encounter', ["Unova Route 3 Area"], [], []],
  [506, 'white', 'gen5-random', ["Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [506, 'white2', 'gen5-random', ["Floccesy Ranch Inner"], [], []],
  [507, 'black', 'gen5-double-encounter', ["Cold Storage Area","Unova Route 1 Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [507, 'black', 'gen5-random', ["Cold Storage Area","P2 Laboratory Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [507, 'black2', 'gen5-double-encounter', ["Unova Route 1 Area","Unova Route 3 Area"], [], []],
  [507, 'black2', 'gen5-random', ["P2 Laboratory Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [507, 'white', 'gen5-double-encounter', ["Cold Storage Area","Unova Route 1 Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [507, 'white', 'gen5-random', ["Cold Storage Area","P2 Laboratory Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [507, 'white2', 'gen5-double-encounter', ["Unova Route 1 Area","Unova Route 3 Area"], [], []],
  [507, 'white2', 'gen5-random', ["P2 Laboratory Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [508, 'black', 'gen5-rustling-grass', ["Cold Storage Area","P2 Laboratory Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [508, 'black2', 'gen5-rustling-grass', ["P2 Laboratory Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [508, 'white', 'gen5-rustling-grass', ["Cold Storage Area","P2 Laboratory Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [508, 'white2', 'gen5-rustling-grass', ["P2 Laboratory Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [509, 'black', 'gen5-double-encounter', ["Unova Route 3 Area"], [], []],
  [509, 'black', 'gen5-random', ["Dreamyard Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [509, 'black2', 'gen5-double-encounter', ["Unova Route 3 Area","Unova Route 20 Area"], [], []],
  [509, 'black2', 'gen5-random', ["Unova Route 3 Area","Unova Route 19 Area","Unova Route 20 Area"], [], []],
  [509, 'white', 'gen5-double-encounter', ["Unova Route 3 Area"], [], []],
  [509, 'white', 'gen5-random', ["Dreamyard Area","Unova Route 2 Area","Unova Route 3 Area"], [], []],
  [509, 'white2', 'gen5-double-encounter', ["Unova Route 3 Area","Unova Route 20 Area"], [], []],
  [509, 'white2', 'gen5-random', ["Unova Route 3 Area","Unova Route 19 Area","Unova Route 20 Area"], [], []],
  [510, 'black', 'gen5-double-encounter', ["Dreamyard Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [510, 'black', 'gen5-random', ["Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [510, 'black2', 'gen5-double-encounter', ["Dreamyard Area","Dreamyard B1f","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [510, 'black2', 'gen5-random', ["Dreamyard Area","Unova Route 2 Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [510, 'white', 'gen5-double-encounter', ["Dreamyard Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [510, 'white', 'gen5-random', ["Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [510, 'white2', 'gen5-double-encounter', ["Dreamyard Area","Dreamyard B1f","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [510, 'white2', 'gen5-random', ["Dreamyard Area","Unova Route 2 Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [511, 'black', 'gen5-gift', ["Dreamyard Area"], [], []],
  [511, 'black', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [511, 'black2', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [511, 'white', 'gen5-gift', ["Dreamyard Area"], [], []],
  [511, 'white', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [511, 'white2', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [513, 'black', 'gen5-gift', ["Dreamyard Area"], [], []],
  [513, 'black', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [513, 'black2', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [513, 'white', 'gen5-gift', ["Dreamyard Area"], [], []],
  [513, 'white', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [513, 'white2', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [515, 'black', 'gen5-gift', ["Dreamyard Area"], [], []],
  [515, 'black', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [515, 'black2', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [515, 'white', 'gen5-gift', ["Dreamyard Area"], [], []],
  [515, 'white', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [515, 'white2', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [517, 'black', 'gen5-double-encounter', ["Dreamyard Area","Dreamyard B1f"], [], []],
  [517, 'black', 'gen5-random', ["Dreamyard Area"], [], []],
  [517, 'black2', 'gen5-double-encounter', ["Dreamyard Area","Dreamyard B1f"], [], []],
  [517, 'black2', 'gen5-random', ["Dreamyard Area"], [], []],
  [517, 'white', 'gen5-double-encounter', ["Dreamyard Area","Dreamyard B1f"], [], []],
  [517, 'white', 'gen5-random', ["Dreamyard Area"], [], []],
  [517, 'white2', 'gen5-double-encounter', ["Dreamyard Area","Dreamyard B1f"], [], []],
  [517, 'white2', 'gen5-random', ["Dreamyard Area"], [], []],
  [518, 'black', 'gen5-rustling-grass', ["Dreamyard Area"], [], []],
  [518, 'black', 'gen5-soft-reset', ["Dreamyard Area","Dreamyard B1f"], [], []],
  [518, 'black2', 'gen5-rustling-grass', ["Dreamyard Area"], [], []],
  [518, 'white', 'gen5-rustling-grass', ["Dreamyard Area"], [], []],
  [518, 'white', 'gen5-soft-reset', ["Dreamyard Area","Dreamyard B1f"], [], []],
  [518, 'white2', 'gen5-rustling-grass', ["Dreamyard Area"], [], []],
  [519, 'black', 'gen5-double-encounter', ["Pinwheel Forest Outside","Unova Route 3 Area"], [], []],
  [519, 'black', 'gen5-random', ["Pinwheel Forest Outside","Pinwheel Forest Inside","Unova Route 3 Area"], [], []],
  [519, 'black2', 'gen5-double-encounter', ["Castelia City Area","Unova Route 20 Area"], [], []],
  [519, 'black2', 'gen5-random', ["Castelia City Area","Floccesy Ranch Inner","Virbank Complex Outer","Unova Route 20 Area"], [], []],
  [519, 'white', 'gen5-double-encounter', ["Pinwheel Forest Outside","Unova Route 3 Area"], [], []],
  [519, 'white', 'gen5-random', ["Pinwheel Forest Outside","Pinwheel Forest Inside","Unova Route 3 Area"], [], []],
  [519, 'white2', 'gen5-double-encounter', ["Castelia City Area","Unova Route 20 Area"], [], []],
  [519, 'white2', 'gen5-random', ["Castelia City Area","Floccesy Ranch Inner","Virbank Complex Outer","Unova Route 20 Area"], [], []],
  [520, 'black', 'gen5-double-encounter', ["Pinwheel Forest Inside","Dragonspiral Tower Outside","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Lostlorn Forest Area"], [], []],
  [520, 'black', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Lostlorn Forest Area"], [], []],
  [520, 'black2', 'gen5-double-encounter', ["Dragonspiral Tower Outside","Unova Route 3 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 79"], [], []],
  [520, 'black2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 3 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 79"], [], []],
  [520, 'white', 'gen5-double-encounter', ["Pinwheel Forest Inside","Dragonspiral Tower Outside","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Lostlorn Forest Area"], [], []],
  [520, 'white', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Lostlorn Forest Area"], [], []],
  [520, 'white2', 'gen5-double-encounter', ["Dragonspiral Tower Outside","Unova Route 3 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 79"], [], []],
  [520, 'white2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 3 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 79"], [], []],
  [521, 'black', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Lostlorn Forest Area"], [], []],
  [521, 'black2', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 3 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 79"], [], []],
  [521, 'white', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Lostlorn Forest Area"], [], []],
  [521, 'white2', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 3 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 12 Area","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 79"], [], []],
  [522, 'black', 'gen5-double-encounter', ["Unova Route 3 Area"], [], []],
  [522, 'black', 'gen5-random', ["Unova Route 3 Area"], [], []],
  [522, 'white', 'gen5-double-encounter', ["Unova Route 3 Area"], [], []],
  [522, 'white', 'gen5-random', ["Unova Route 3 Area"], [], []],
  [523, 'black', 'gen5-double-encounter', ["Unova Route 7 Area"], [], []],
  [523, 'black', 'gen5-random', ["Unova Route 7 Area"], [], []],
  [523, 'black2', 'gen5-double-encounter', ["Unova Route 3 Area","Unova Route 7 Area"], [], []],
  [523, 'black2', 'gen5-random', ["Unova Route 3 Area","Unova Route 7 Area"], [], []],
  [523, 'white', 'gen5-double-encounter', ["Unova Route 7 Area"], [], []],
  [523, 'white', 'gen5-random', ["Unova Route 7 Area"], [], []],
  [523, 'white2', 'gen5-double-encounter', ["Unova Route 3 Area","Unova Route 7 Area"], [], []],
  [523, 'white2', 'gen5-random', ["Unova Route 3 Area","Unova Route 7 Area"], [], []],
  [524, 'black', 'gen5-random', ["Wellspring Cave Area"], [], []],
  [524, 'black2', 'gen5-random', ["Relic Passage Castelia Sewers Entrance"], [], []],
  [524, 'white', 'gen5-random', ["Wellspring Cave Area"], [], []],
  [524, 'white2', 'gen5-random', ["Relic Passage Castelia Sewers Entrance"], [], []],
  [525, 'black', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Twist Mountain B1f 3f","Unova Victory Road Unknown Area 53","Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road 1f Unknown Room","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area","Giant Chasm Area","Giant Chasm Forest Cave","Mistralton Cave Area","Guidance Chamber Area","Challengers Cave 1f","Challengers Cave B1f","Challengers Cave B2f"], [], []],
  [525, 'black2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Twist Mountain B1f 3f","Wellspring Cave Area","Mistralton Cave Area","Guidance Chamber Area","Unova Victory Road 7f","Unova Victory Road 2 Unknown Area 74","Unova Victory Road 2 Unknown Area 75","Reversal Mountain Unknown Area 49","Reversal Mountain Unknown Area 50","Reversal Mountain Unknown Area 51","Reversal Mountain Unknown Area 52","Reversal Mountain Unknown Area 53","Reversal Mountain Unknown Area 54","Reversal Mountain Unknown Area 55","Reversal Mountain Unknown Area 56","Reversal Mountain Unknown Area 57","Reversal Mountain Unknown Area 58","Reversal Mountain Unknown Area 59","Reversal Mountain Unknown Area 60","Relic Passage Relic Castle Entrance","Relic Passage Pwt Entrance","Clay Tunnel Area","Underground Ruins Area","Rocky Mountain Room Area","Glacier Room Area","Iron Room Area","Seaside Cave 1f","Seaside Cave B1f"], [], []],
  [525, 'white', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Twist Mountain B1f 3f","Unova Victory Road Unknown Area 53","Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road 1f Unknown Room","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area","Giant Chasm Area","Giant Chasm Forest Cave","Mistralton Cave Area","Guidance Chamber Area","Challengers Cave 1f","Challengers Cave B1f","Challengers Cave B2f"], [], []],
  [525, 'white2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Twist Mountain B1f 3f","Wellspring Cave Area","Mistralton Cave Area","Guidance Chamber Area","Unova Victory Road 7f","Unova Victory Road 2 Unknown Area 74","Unova Victory Road 2 Unknown Area 75","Reversal Mountain Unknown Area 49","Reversal Mountain Unknown Area 50","Reversal Mountain Unknown Area 51","Reversal Mountain Unknown Area 52","Reversal Mountain Unknown Area 53","Reversal Mountain Unknown Area 54","Reversal Mountain Unknown Area 55","Reversal Mountain Unknown Area 56","Reversal Mountain Unknown Area 57","Reversal Mountain Unknown Area 58","Reversal Mountain Unknown Area 59","Reversal Mountain Unknown Area 60","Relic Passage Relic Castle Entrance","Relic Passage Pwt Entrance","Clay Tunnel Area","Underground Ruins Area","Rocky Mountain Room Area","Glacier Room Area","Iron Room Area","Seaside Cave 1f","Seaside Cave B1f"], [], []],
  [527, 'black', 'gen5-random', ["Twist Mountain B1f 3f","Unova Victory Road Unknown Area 53","Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road 1f Unknown Room","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area","Wellspring Cave Area","Mistralton Cave Area","Guidance Chamber Area","Challengers Cave 1f","Challengers Cave B1f","Challengers Cave B2f"], [], []],
  [527, 'black2', 'gen5-random', ["Twist Mountain B1f 3f","Wellspring Cave Area","Mistralton Cave Area","Guidance Chamber Area","Reversal Mountain Unknown Area 49","Reversal Mountain Unknown Area 50","Reversal Mountain Unknown Area 51","Reversal Mountain Unknown Area 52","Reversal Mountain Unknown Area 53","Reversal Mountain Unknown Area 54","Reversal Mountain Unknown Area 55","Reversal Mountain Unknown Area 56","Reversal Mountain Unknown Area 57","Reversal Mountain Unknown Area 58","Reversal Mountain Unknown Area 59","Reversal Mountain Unknown Area 60","Relic Passage Castelia Sewers Entrance","Relic Passage Relic Castle Entrance","Relic Passage Pwt Entrance","Clay Tunnel Area","Underground Ruins Area","Rocky Mountain Room Area","Glacier Room Area","Iron Room Area","Seaside Cave 1f","Seaside Cave B1f"], [], []],
  [527, 'white', 'gen5-random', ["Twist Mountain B1f 3f","Unova Victory Road Unknown Area 53","Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road 1f Unknown Room","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area","Wellspring Cave Area","Mistralton Cave Area","Guidance Chamber Area","Challengers Cave 1f","Challengers Cave B1f","Challengers Cave B2f"], [], []],
  [527, 'white2', 'gen5-random', ["Twist Mountain B1f 3f","Wellspring Cave Area","Mistralton Cave Area","Guidance Chamber Area","Reversal Mountain Unknown Area 49","Reversal Mountain Unknown Area 50","Reversal Mountain Unknown Area 51","Reversal Mountain Unknown Area 52","Reversal Mountain Unknown Area 53","Reversal Mountain Unknown Area 54","Reversal Mountain Unknown Area 55","Reversal Mountain Unknown Area 56","Reversal Mountain Unknown Area 57","Reversal Mountain Unknown Area 58","Reversal Mountain Unknown Area 59","Reversal Mountain Unknown Area 60","Relic Passage Castelia Sewers Entrance","Relic Passage Relic Castle Entrance","Relic Passage Pwt Entrance","Clay Tunnel Area","Underground Ruins Area","Rocky Mountain Room Area","Glacier Room Area","Iron Room Area","Seaside Cave 1f","Seaside Cave B1f"], [], []],
  [529, 'black', 'gen5-dust-clouds', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Twist Mountain B1f 3f","Wellspring Cave Area","Mistralton Cave Area","Guidance Chamber Area"], [], []],
  [529, 'black2', 'gen5-dust-clouds', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Mistralton Cave Area","Guidance Chamber Area","Relic Passage Castelia Sewers Entrance","Relic Passage Relic Castle Entrance","Relic Passage Pwt Entrance"], [], []],
  [529, 'white', 'gen5-dust-clouds', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Twist Mountain B1f 3f","Wellspring Cave Area","Mistralton Cave Area","Guidance Chamber Area"], [], []],
  [529, 'white2', 'gen5-dust-clouds', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Mistralton Cave Area","Guidance Chamber Area","Relic Passage Castelia Sewers Entrance","Relic Passage Relic Castle Entrance","Relic Passage Pwt Entrance"], [], []],
  [530, 'black', 'gen5-dust-clouds', ["Unova Victory Road Unknown Area 53","Unova Victory Road 1f Unknown Room","Giant Chasm Area","Giant Chasm Forest Cave","Challengers Cave 1f","Challengers Cave B1f","Challengers Cave B2f"], [], []],
  [530, 'black', 'gen5-rustling-grass', ["Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area"], [], []],
  [530, 'black2', 'gen5-dust-clouds', ["Twist Mountain B1f 3f","Giant Chasm Area","Wellspring Cave Area","Unova Victory Road 7f","Unova Victory Road 2 Unknown Area 74","Unova Victory Road 2 Unknown Area 75","Unova Victory Road 2 Unknown Area 77","Unova Victory Road 2 Unknown Area 80","Reversal Mountain Unknown Area 49","Reversal Mountain Unknown Area 50","Reversal Mountain Unknown Area 51","Reversal Mountain Unknown Area 52","Reversal Mountain Unknown Area 53","Reversal Mountain Unknown Area 54","Reversal Mountain Unknown Area 55","Reversal Mountain Unknown Area 56","Reversal Mountain Unknown Area 57","Reversal Mountain Unknown Area 58","Reversal Mountain Unknown Area 59","Reversal Mountain Unknown Area 60","Clay Tunnel Area","Underground Ruins Area","Rocky Mountain Room Area","Glacier Room Area","Iron Room Area","Seaside Cave 1f","Seaside Cave B1f"], [], []],
  [530, 'white', 'gen5-dust-clouds', ["Unova Victory Road Unknown Area 53","Unova Victory Road 1f Unknown Room","Giant Chasm Area","Giant Chasm Forest Cave","Challengers Cave 1f","Challengers Cave B1f","Challengers Cave B2f"], [], []],
  [530, 'white', 'gen5-rustling-grass', ["Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area"], [], []],
  [530, 'white2', 'gen5-dust-clouds', ["Twist Mountain B1f 3f","Giant Chasm Area","Wellspring Cave Area","Unova Victory Road 7f","Unova Victory Road 2 Unknown Area 74","Unova Victory Road 2 Unknown Area 75","Unova Victory Road 2 Unknown Area 77","Unova Victory Road 2 Unknown Area 80","Reversal Mountain Unknown Area 49","Reversal Mountain Unknown Area 50","Reversal Mountain Unknown Area 51","Reversal Mountain Unknown Area 52","Reversal Mountain Unknown Area 53","Reversal Mountain Unknown Area 54","Reversal Mountain Unknown Area 55","Reversal Mountain Unknown Area 56","Reversal Mountain Unknown Area 57","Reversal Mountain Unknown Area 58","Reversal Mountain Unknown Area 59","Reversal Mountain Unknown Area 60","Clay Tunnel Area","Underground Ruins Area","Rocky Mountain Room Area","Glacier Room Area","Iron Room Area","Seaside Cave 1f","Seaside Cave B1f"], [], []],
  [531, 'black', 'gen5-rustling-grass', ["Dreamyard Area","Pinwheel Forest Outside","Pinwheel Forest Inside","Cold Storage Area","Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside","Giant Chasm Forest","P2 Laboratory Area","Village Bridge Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area","Unova Route 5 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 9 Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 11 Area","Unova Route 12 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Unova Route 15 Area","Unova Route 16 Area","Lostlorn Forest Area","Unova Route 18 Area"], [], []],
  [531, 'black2', 'gen5-rustling-grass', ["Dreamyard Area","Pinwheel Forest Outside","Pinwheel Forest Inside","Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside","Giant Chasm Forest","Giant Chasm Forest Cave","P2 Laboratory Area","Village Bridge Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area","Unova Route 5 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 9 Area","Unova Route 11 Area","Unova Route 12 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Unova Route 15 Area","Unova Route 16 Area","Lostlorn Forest Area","Unova Route 18 Area","Castelia City Area","Unova Victory Road 2 Unknown Area 72","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 76","Unova Victory Road 2 Unknown Area 79","Floccesy Ranch Inner","Virbank Complex Outer","Virbank Complex Inner","Reversal Mountain Unknown Area 48","Nature Sanctuary Area","Unova Route 20 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [531, 'white', 'gen5-rustling-grass', ["Dreamyard Area","Pinwheel Forest Outside","Pinwheel Forest Inside","Cold Storage Area","Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside","Giant Chasm Forest","P2 Laboratory Area","Village Bridge Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area","Unova Route 5 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 9 Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 11 Area","Unova Route 12 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Unova Route 15 Area","Unova Route 16 Area","Lostlorn Forest Area","Unova Route 18 Area"], [], []],
  [531, 'white2', 'gen5-rustling-grass', ["Dreamyard Area","Pinwheel Forest Outside","Pinwheel Forest Inside","Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside","Giant Chasm Forest","Giant Chasm Forest Cave","P2 Laboratory Area","Village Bridge Area","Unova Route 1 Area","Unova Route 2 Area","Unova Route 3 Area","Unova Route 5 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 9 Area","Unova Route 11 Area","Unova Route 12 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Unova Route 15 Area","Unova Route 16 Area","Lostlorn Forest Area","Unova Route 18 Area","Castelia City Area","Unova Victory Road 2 Unknown Area 72","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 76","Unova Victory Road 2 Unknown Area 79","Floccesy Ranch Inner","Virbank Complex Outer","Virbank Complex Inner","Reversal Mountain Unknown Area 48","Nature Sanctuary Area","Unova Route 20 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [532, 'black', 'gen5-double-encounter', ["Pinwheel Forest Outside","Cold Storage Area"], [], []],
  [532, 'black', 'gen5-random', ["Pinwheel Forest Outside","Cold Storage Area"], [], []],
  [532, 'black2', 'gen5-random', ["Relic Passage Castelia Sewers Entrance"], [], []],
  [532, 'white', 'gen5-double-encounter', ["Pinwheel Forest Outside","Cold Storage Area"], [], []],
  [532, 'white', 'gen5-random', ["Pinwheel Forest Outside","Cold Storage Area"], [], []],
  [532, 'white2', 'gen5-random', ["Relic Passage Castelia Sewers Entrance"], [], []],
  [533, 'black', 'gen5-random', ["Twist Mountain B1f 3f"], [], []],
  [533, 'black2', 'gen5-double-encounter', ["Pinwheel Forest Outside","Unova Victory Road 2 Unknown Area 76"], [], []],
  [533, 'black2', 'gen5-random', ["Pinwheel Forest Outside","Twist Mountain B1f 3f","Unova Victory Road 2 Unknown Area 76","Relic Passage Relic Castle Entrance","Relic Passage Pwt Entrance"], [], []],
  [533, 'white', 'gen5-random', ["Twist Mountain B1f 3f"], [], []],
  [533, 'white2', 'gen5-double-encounter', ["Pinwheel Forest Outside","Unova Victory Road 2 Unknown Area 76"], [], []],
  [533, 'white2', 'gen5-random', ["Pinwheel Forest Outside","Twist Mountain B1f 3f","Unova Victory Road 2 Unknown Area 76","Relic Passage Relic Castle Entrance","Relic Passage Pwt Entrance"], [], []],
  [535, 'black', 'gen5-double-encounter', ["Pinwheel Forest Outside"], [], []],
  [535, 'black', 'gen5-random', ["Pinwheel Forest Outside"], [], []],
  [535, 'white', 'gen5-double-encounter', ["Pinwheel Forest Outside"], [], []],
  [535, 'white', 'gen5-random', ["Pinwheel Forest Outside"], [], []],
  [536, 'black', 'gen5-random', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [536, 'black2', 'gen5-double-encounter', ["Pinwheel Forest Outside"], [], []],
  [536, 'black2', 'gen5-random', ["Icirrus City Area","Pinwheel Forest Outside","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [536, 'black2', 'gen5-rippling-waters', ["Unova Route 8 Area"], [], []],
  [536, 'white', 'gen5-random', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [536, 'white2', 'gen5-double-encounter', ["Pinwheel Forest Outside"], [], []],
  [536, 'white2', 'gen5-random', ["Icirrus City Area","Pinwheel Forest Outside","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [536, 'white2', 'gen5-rippling-waters', ["Unova Route 8 Area"], [], []],
  [537, 'black', 'gen5-rippling-waters', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [537, 'black2', 'gen5-rippling-waters', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [537, 'black2', 'gen5-rustling-grass', ["Pinwheel Forest Outside"], [], []],
  [537, 'white', 'gen5-rippling-waters', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [537, 'white2', 'gen5-rippling-waters', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [537, 'white2', 'gen5-rustling-grass', ["Pinwheel Forest Outside"], [], []],
  [538, 'black', 'gen5-rustling-grass', ["Pinwheel Forest Outside","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [538, 'black2', 'gen5-double-encounter', ["Unova Victory Road 2 Unknown Area 76"], [], []],
  [538, 'black2', 'gen5-random', ["Unova Victory Road 2 Unknown Area 76"], [], []],
  [538, 'black2', 'gen5-rustling-grass', ["Pinwheel Forest Outside","Unova Route 15 Area","Unova Route 18 Area","Unova Route 23 Area"], [], []],
  [538, 'white', 'gen5-double-encounter', ["Pinwheel Forest Outside","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [538, 'white', 'gen5-random', ["Pinwheel Forest Outside","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [538, 'white2', 'gen5-double-encounter', ["Pinwheel Forest Outside","Unova Route 15 Area","Unova Route 18 Area","Unova Victory Road 2 Unknown Area 76","Unova Route 23 Area"], [], []],
  [538, 'white2', 'gen5-random', ["Pinwheel Forest Outside","Unova Route 15 Area","Unova Route 18 Area","Unova Victory Road 2 Unknown Area 76","Unova Route 23 Area"], [], []],
  [539, 'black', 'gen5-double-encounter', ["Pinwheel Forest Outside","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [539, 'black', 'gen5-random', ["Pinwheel Forest Outside","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [539, 'black2', 'gen5-double-encounter', ["Pinwheel Forest Outside","Unova Route 15 Area","Unova Route 18 Area","Unova Route 23 Area"], [], []],
  [539, 'black2', 'gen5-random', ["Pinwheel Forest Outside","Unova Route 15 Area","Unova Route 18 Area","Unova Route 23 Area"], [], []],
  [539, 'black2', 'gen5-rustling-grass', ["Unova Victory Road 2 Unknown Area 76"], [], []],
  [539, 'white', 'gen5-rustling-grass', ["Pinwheel Forest Outside","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [539, 'white2', 'gen5-rustling-grass', ["Pinwheel Forest Outside","Unova Route 15 Area","Unova Route 18 Area","Unova Victory Road 2 Unknown Area 76","Unova Route 23 Area"], [], []],
  [540, 'black', 'gen5-random', ["Pinwheel Forest Inside"], [], []],
  [540, 'black2', 'gen5-double-encounter', ["Unova Route 12 Area","Unova Route 20 Area"], [], []],
  [540, 'black2', 'gen5-random', ["Unova Route 12 Area","Unova Route 20 Area"], [], []],
  [540, 'white', 'gen5-random', ["Pinwheel Forest Inside"], [], []],
  [540, 'white2', 'gen5-double-encounter', ["Unova Route 12 Area","Unova Route 20 Area"], [], []],
  [540, 'white2', 'gen5-random', ["Unova Route 12 Area","Unova Route 20 Area"], [], []],
  [541, 'black', 'gen5-double-encounter', ["Pinwheel Forest Inside","Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [541, 'black', 'gen5-random', ["Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [541, 'black2', 'gen5-double-encounter', ["Pinwheel Forest Inside","Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [541, 'black2', 'gen5-random', ["Pinwheel Forest Inside","Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [541, 'white', 'gen5-double-encounter', ["Pinwheel Forest Inside","Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [541, 'white', 'gen5-random', ["Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [541, 'white2', 'gen5-double-encounter', ["Pinwheel Forest Inside","Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [541, 'white2', 'gen5-random', ["Pinwheel Forest Inside","Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [542, 'black', 'gen5-rustling-grass', ["Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [542, 'black2', 'gen5-rustling-grass', ["Unova Route 6 Area","Unova Route 12 Area","Lostlorn Forest Area"], [], []],
  [542, 'white', 'gen5-rustling-grass', ["Unova Route 6 Area","Lostlorn Forest Area"], [], []],
  [542, 'white2', 'gen5-rustling-grass', ["Unova Route 6 Area","Unova Route 12 Area","Lostlorn Forest Area"], [], []],
  [543, 'black', 'gen5-double-encounter', ["Lostlorn Forest Area"], [], []],
  [543, 'black', 'gen5-random', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [543, 'black2', 'gen5-double-encounter', ["Unova Route 20 Area"], [], []],
  [543, 'black2', 'gen5-random', ["Lostlorn Forest Area"], [], []],
  [543, 'white', 'gen5-double-encounter', ["Lostlorn Forest Area"], [], []],
  [543, 'white', 'gen5-random', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [543, 'white2', 'gen5-double-encounter', ["Unova Route 20 Area"], [], []],
  [543, 'white2', 'gen5-random', ["Lostlorn Forest Area"], [], []],
  [544, 'black', 'gen5-double-encounter', ["Pinwheel Forest Inside"], [], []],
  [544, 'black2', 'gen5-double-encounter', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [544, 'black2', 'gen5-random', ["Pinwheel Forest Inside"], [], []],
  [544, 'white', 'gen5-double-encounter', ["Pinwheel Forest Inside"], [], []],
  [544, 'white2', 'gen5-double-encounter', ["Pinwheel Forest Inside","Lostlorn Forest Area"], [], []],
  [544, 'white2', 'gen5-random', ["Pinwheel Forest Inside"], [], []],
  [545, 'black2', 'gen5-rustling-grass', ["Pinwheel Forest Inside"], [], []],
  [545, 'white2', 'gen5-rustling-grass', ["Pinwheel Forest Inside"], [], []],
  [546, 'black', 'gen5-double-encounter', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area"], [], []],
  [546, 'black', 'gen5-random', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area"], [], []],
  [546, 'black2', 'gen5-double-encounter', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area","Castelia City Area","Unova Victory Road 2 Unknown Area 72"], [], []],
  [546, 'black2', 'gen5-random', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area","Castelia City Area","Unova Victory Road 2 Unknown Area 72"], [], []],
  [547, 'black', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area"], [], []],
  [547, 'black2', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area","Castelia City Area","Unova Victory Road 2 Unknown Area 72"], [], []],
  [548, 'white', 'gen5-double-encounter', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area"], [], []],
  [548, 'white', 'gen5-random', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area"], [], []],
  [548, 'white2', 'gen5-double-encounter', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area","Castelia City Area","Unova Victory Road 2 Unknown Area 72"], [], []],
  [548, 'white2', 'gen5-random', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area","Castelia City Area","Unova Victory Road 2 Unknown Area 72"], [], []],
  [549, 'white', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area"], [], []],
  [549, 'white2', 'gen5-rustling-grass', ["Pinwheel Forest Inside","Abundant Shrine Area","Lostlorn Forest Area","Castelia City Area","Unova Victory Road 2 Unknown Area 72"], [], []],
  [550, 'black', 'gen5-random', ["Striaton City Area","Pinwheel Forest Inside","Dragonspiral Tower Outside","Unova Victory Road Unknown Area 53","Unova Victory Road 1f Unknown Room","Giant Chasm Area","Giant Chasm Forest Cave","Village Bridge Area","Unova Route 1 Area","Unova Route 3 Area","Wellspring Cave Area","Unova Route 6 Area","Challengers Cave B2f","Unova Route 11 Area","Unova Route 14 Area","Abundant Shrine Area","Lostlorn Forest Area"], [], []],
  [550, 'black', 'gen5-super-rod', ["Striaton City Area","Pinwheel Forest Inside","Dragonspiral Tower Outside","Unova Victory Road Unknown Area 53","Unova Victory Road 1f Unknown Room","Giant Chasm Area","Giant Chasm Forest Cave","Village Bridge Area","Unova Route 1 Area","Unova Route 3 Area","Wellspring Cave Area","Unova Route 6 Area","Challengers Cave B2f","Unova Route 11 Area","Unova Route 14 Area","Abundant Shrine Area","Lostlorn Forest Area"], [], []],
  [550, 'black2', 'gen5-random', ["Striaton City Area","Pinwheel Forest Inside","Dragonspiral Tower Outside","Giant Chasm Area","Village Bridge Area","Unova Route 1 Area","Unova Route 3 Area","Wellspring Cave Area","Unova Route 6 Area","Unova Route 11 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Lostlorn Forest Area","Undella Town Area","Aspertia City Area","Humilau City Area","Unova Victory Road 2 Unknown Area 71","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 75","Unova Victory Road 2 Unknown Area 78","Unova Victory Road 2 Unknown Area 79","Floccesy Ranch Outer","Floccesy Ranch Inner","Relic Passage Relic Castle Entrance","Clay Tunnel Area","Nature Sanctuary Area","Unova Route 19 Area","Unova Route 20 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [550, 'black2', 'gen5-super-rod', ["Striaton City Area","Pinwheel Forest Inside","Dragonspiral Tower Outside","Giant Chasm Area","Village Bridge Area","Unova Route 1 Area","Unova Route 3 Area","Wellspring Cave Area","Unova Route 6 Area","Unova Route 11 Area","Unova Route 14 Area","Abundant Shrine Area","Lostlorn Forest Area","Aspertia City Area","Unova Victory Road 2 Unknown Area 71","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 75","Unova Victory Road 2 Unknown Area 78","Unova Victory Road 2 Unknown Area 79","Floccesy Ranch Outer","Floccesy Ranch Inner","Relic Passage Relic Castle Entrance","Clay Tunnel Area","Nature Sanctuary Area","Unova Route 19 Area","Unova Route 20 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [550, 'white', 'gen5-rippling-waters', ["Striaton City Area","Pinwheel Forest Inside","Dragonspiral Tower Outside","Unova Victory Road Unknown Area 53","Unova Victory Road 1f Unknown Room","Giant Chasm Area","Giant Chasm Forest Cave","Village Bridge Area","Unova Route 1 Area","Unova Route 3 Area","Wellspring Cave Area","Unova Route 6 Area","Challengers Cave B2f","Unova Route 11 Area","Unova Route 14 Area","Abundant Shrine Area","Lostlorn Forest Area"], [], []],
  [550, 'white2', 'gen5-rippling-waters', ["Striaton City Area","Pinwheel Forest Inside","Dragonspiral Tower Outside","Giant Chasm Area","Village Bridge Area","Unova Route 1 Area","Unova Route 3 Area","Wellspring Cave Area","Unova Route 6 Area","Unova Route 11 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Lostlorn Forest Area","Undella Town Area","Aspertia City Area","Humilau City Area","Unova Victory Road 2 Unknown Area 71","Unova Victory Road 2 Unknown Area 73","Unova Victory Road 2 Unknown Area 75","Unova Victory Road 2 Unknown Area 78","Unova Victory Road 2 Unknown Area 79","Floccesy Ranch Outer","Floccesy Ranch Inner","Relic Passage Relic Castle Entrance","Clay Tunnel Area","Nature Sanctuary Area","Unova Route 19 Area","Unova Route 20 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [551, 'black', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Relic Castle A","Unova Route 4 Area"], [], []],
  [551, 'black2', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Relic Castle A","Relic Castle C","Unova Route 4 Area"], [], []],
  [551, 'white', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Relic Castle A","Unova Route 4 Area"], [], []],
  [551, 'white2', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Relic Castle A","Relic Castle C","Unova Route 4 Area"], [], []],
  [552, 'black', 'gen5-random', ["Relic Castle B","Relic Castle C"], [], []],
  [552, 'black2', 'gen5-random', ["Relic Castle C"], [], []],
  [552, 'white', 'gen5-random', ["Relic Castle B","Relic Castle C"], [], []],
  [552, 'white2', 'gen5-random', ["Relic Castle C"], [], []],
  [554, 'black', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Unova Route 4 Area"], [], []],
  [554, 'black2', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Unova Route 4 Area"], [], []],
  [554, 'white', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Unova Route 4 Area"], [], []],
  [554, 'white2', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Unova Route 4 Area"], [], []],
  [556, 'black', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area"], [], []],
  [556, 'black2', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area"], [], []],
  [556, 'white', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area"], [], []],
  [556, 'white2', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area"], [], []],
  [557, 'black', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Unova Route 18 Area"], [], []],
  [557, 'black2', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area"], [], []],
  [557, 'white', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area","Unova Route 18 Area"], [], []],
  [557, 'white2', 'gen5-random', ["Desert Resort Entrance","Desert Resort Area"], [], []],
  [558, 'black', 'gen5-double-encounter', ["Unova Route 18 Area"], [], []],
  [558, 'black2', 'gen5-double-encounter', ["Unova Route 18 Area"], [], []],
  [558, 'black2', 'gen5-random', ["Unova Route 18 Area"], [], []],
  [558, 'black2', 'gen5-soft-reset', ["Seaside Cave 1f"], [], []],
  [558, 'white', 'gen5-double-encounter', ["Unova Route 18 Area"], [], []],
  [558, 'white2', 'gen5-double-encounter', ["Unova Route 18 Area"], [], []],
  [558, 'white2', 'gen5-random', ["Unova Route 18 Area"], [], []],
  [558, 'white2', 'gen5-soft-reset', ["Seaside Cave 1f"], [], []],
  [559, 'black', 'gen5-double-encounter', ["Unova Route 1 Area","Unova Route 18 Area"], [], []],
  [559, 'black', 'gen5-random', ["Desert Resort Entrance","P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area"], [], []],
  [559, 'black2', 'gen5-random', ["Desert Resort Entrance","Unova Route 4 Area"], [], []],
  [559, 'white', 'gen5-double-encounter', ["Unova Route 1 Area","Unova Route 18 Area"], [], []],
  [559, 'white', 'gen5-random', ["Desert Resort Entrance","P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area"], [], []],
  [559, 'white2', 'gen5-random', ["Desert Resort Entrance","Unova Route 4 Area"], [], []],
  [560, 'black2', 'gen5-double-encounter', ["Unova Route 1 Area","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [560, 'black2', 'gen5-random', ["P2 Laboratory Area","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [560, 'white2', 'gen5-double-encounter', ["Unova Route 1 Area","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [560, 'white2', 'gen5-random', ["P2 Laboratory Area","Unova Route 15 Area","Unova Route 18 Area"], [], []],
  [561, 'black', 'gen5-random', ["Desert Resort Area"], [], []],
  [561, 'black2', 'gen5-random', ["Desert Resort Area"], [], []],
  [561, 'white', 'gen5-random', ["Desert Resort Area"], [], []],
  [561, 'white2', 'gen5-random', ["Desert Resort Area"], [], []],
  [562, 'black', 'gen5-random', ["Relic Castle A"], [], []],
  [562, 'black2', 'gen5-random', ["Relic Castle A","Relic Castle C"], [], []],
  [562, 'white', 'gen5-random', ["Relic Castle A"], [], []],
  [562, 'white2', 'gen5-random', ["Relic Castle A","Relic Castle C"], [], []],
  [563, 'black', 'gen5-random', ["Relic Castle B","Relic Castle C"], [], []],
  [563, 'white', 'gen5-random', ["Relic Castle B","Relic Castle C"], [], []],
  [564, 'black', 'gen5-fossil-restore', ["Nacrene City Nacrene Museum"], [], []],
  [564, 'black2', 'gen5-fossil-restore', ["Nacrene City Nacrene Museum"], [], []],
  [564, 'white', 'gen5-fossil-restore', ["Nacrene City Nacrene Museum"], [], []],
  [564, 'white2', 'gen5-fossil-restore', ["Nacrene City Nacrene Museum"], [], []],
  [566, 'black', 'gen5-fossil-restore', ["Nacrene City Nacrene Museum"], [], []],
  [566, 'black2', 'gen5-fossil-restore', ["Nacrene City Nacrene Museum"], [], []],
  [566, 'white', 'gen5-fossil-restore', ["Nacrene City Nacrene Museum"], [], []],
  [566, 'white2', 'gen5-fossil-restore', ["Nacrene City Nacrene Museum"], [], []],
  [568, 'black', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [568, 'black', 'gen5-random', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [568, 'black2', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [568, 'black2', 'gen5-random', ["Unova Route 4 Area","Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [568, 'white', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [568, 'white', 'gen5-random', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [568, 'white2', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [568, 'white2', 'gen5-random', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [569, 'black', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [569, 'black', 'gen5-random', ["Unova Route 9 Area"], [], []],
  [569, 'black2', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [569, 'black2', 'gen5-random', ["Unova Route 9 Area"], [], []],
  [569, 'white', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [569, 'white', 'gen5-random', ["Unova Route 9 Area"], [], []],
  [569, 'white2', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [569, 'white2', 'gen5-random', ["Unova Route 9 Area"], [], []],
  [570, 'black', 'gen5-gift', ["Castelia City Game Freak Hq 1f"], [], []],
  [570, 'black2', 'gen5-gift', ["Driftveil City Area"], [], []],
  [570, 'white', 'gen5-gift', ["Castelia City Game Freak Hq 1f"], [], []],
  [570, 'white2', 'gen5-gift', ["Driftveil City Area"], [], []],
  [571, 'black', 'gen5-soft-reset', ["Lostlorn Forest Area"], [], []],
  [571, 'white', 'gen5-soft-reset', ["Lostlorn Forest Area"], [], []],
  [572, 'black', 'gen5-double-encounter', ["Cold Storage Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [572, 'black', 'gen5-random', ["Cold Storage Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [572, 'black2', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [572, 'black2', 'gen5-random', ["Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [572, 'white', 'gen5-double-encounter', ["Cold Storage Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [572, 'white', 'gen5-random', ["Cold Storage Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [572, 'white2', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [572, 'white2', 'gen5-random', ["Unova Route 4 Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [573, 'black', 'gen5-rustling-grass', ["Cold Storage Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [573, 'black2', 'gen5-rustling-grass', ["Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [573, 'white', 'gen5-rustling-grass', ["Cold Storage Area","Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [573, 'white2', 'gen5-rustling-grass', ["Unova Route 5 Area","Unova Route 9 Area","Unova Route 16 Area"], [], []],
  [574, 'black', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [574, 'black', 'gen5-random', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [574, 'black2', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [574, 'black2', 'gen5-random', ["Unova Route 5 Area","Unova Route 16 Area","Strange House 1f","Strange House B1f"], [], []],
  [575, 'black', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [575, 'black', 'gen5-random', ["Unova Route 9 Area"], [], []],
  [575, 'black2', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [575, 'black2', 'gen5-random', ["Unova Route 9 Area","Strange House 1f","Strange House B1f"], [], []],
  [576, 'black', 'gen5-rustling-grass', ["Unova Route 9 Area"], [], []],
  [576, 'black2', 'gen5-rustling-grass', ["Unova Route 9 Area"], [], []],
  [577, 'white', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [577, 'white', 'gen5-random', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [577, 'white2', 'gen5-double-encounter', ["Unova Route 5 Area","Unova Route 16 Area"], [], []],
  [577, 'white2', 'gen5-random', ["Unova Route 5 Area","Unova Route 16 Area","Strange House 1f","Strange House B1f"], [], []],
  [578, 'white', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [578, 'white', 'gen5-random', ["Unova Route 9 Area"], [], []],
  [578, 'white2', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [578, 'white2', 'gen5-random', ["Unova Route 9 Area","Strange House 1f","Strange House B1f"], [], []],
  [579, 'white', 'gen5-rustling-grass', ["Unova Route 9 Area"], [], []],
  [579, 'white2', 'gen5-rustling-grass', ["Unova Route 9 Area"], [], []],
  [580, 'black', 'gen5-rippling-waters', ["Driftveil Drawbridge Area"], [], []],
  [580, 'black2', 'gen5-rippling-waters', ["Driftveil Drawbridge Area"], [], []],
  [580, 'white', 'gen5-rippling-waters', ["Driftveil Drawbridge Area"], [], []],
  [580, 'white2', 'gen5-rippling-waters', ["Driftveil Drawbridge Area"], [], []],
  [581, 'black', 'gen5-rippling-waters', ["Marvelous Bridge Area"], [], []],
  [581, 'black2', 'gen5-rippling-waters', ["Marvelous Bridge Area"], [], []],
  [581, 'white', 'gen5-rippling-waters', ["Marvelous Bridge Area"], [], []],
  [581, 'white2', 'gen5-rippling-waters', ["Marvelous Bridge Area"], [], []],
  [582, 'black', 'gen5-double-encounter', ["Cold Storage Area","Unova Route 6 Area"], [], []],
  [582, 'black', 'gen5-random', ["Cold Storage Area","Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 6 Area"], [], []],
  [582, 'white', 'gen5-double-encounter', ["Cold Storage Area","Unova Route 6 Area"], [], []],
  [582, 'white', 'gen5-random', ["Cold Storage Area","Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 6 Area"], [], []],
  [583, 'black', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [583, 'black2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside"], [], []],
  [583, 'black2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside","Giant Chasm Area"], [], []],
  [583, 'white', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [583, 'white2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside"], [], []],
  [583, 'white2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside","Giant Chasm Area"], [], []],
  [584, 'black2', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside"], [], []],
  [584, 'white2', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside"], [], []],
  [585, 'black', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [585, 'black', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [585, 'black2', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [585, 'black2', 'gen5-gift', ["Unova Route 6 Weather Institute"], [], []],
  [585, 'black2', 'gen5-random', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [585, 'white', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [585, 'white', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [585, 'white2', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [585, 'white2', 'gen5-gift', ["Unova Route 6 Weather Institute"], [], []],
  [585, 'white2', 'gen5-random', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [586, 'black', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [586, 'black2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [586, 'black2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [586, 'white', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [586, 'white2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [586, 'white2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [587, 'black', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside","Village Bridge Area","Unova Route 5 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 9 Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 11 Area","Unova Route 12 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Unova Route 15 Area","Unova Route 16 Area","Lostlorn Forest Area"], [], []],
  [587, 'black2', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Village Bridge Area","Unova Route 5 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 9 Area","Unova Route 11 Area","Unova Route 12 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Unova Route 15 Area","Unova Route 16 Area","Lostlorn Forest Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [587, 'white', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Giant Chasm Outside","Village Bridge Area","Unova Route 5 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 9 Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 11 Area","Unova Route 12 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Unova Route 15 Area","Unova Route 16 Area","Lostlorn Forest Area"], [], []],
  [587, 'white2', 'gen5-rustling-grass', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Village Bridge Area","Unova Route 5 Area","Unova Route 6 Area","Unova Route 7 Area","Unova Route 9 Area","Unova Route 11 Area","Unova Route 12 Area","Unova Route 13 Area","Unova Route 14 Area","Abundant Shrine Area","Unova Route 15 Area","Unova Route 16 Area","Lostlorn Forest Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [588, 'black', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 11 Area"], [], []],
  [588, 'black', 'gen5-random', ["Unova Route 6 Area","Unova Route 11 Area"], [], []],
  [588, 'black2', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 11 Area"], [], []],
  [588, 'black2', 'gen5-random', ["Icirrus City Area","Unova Route 6 Area","Unova Route 8 Area","Moor Of Icirrus Area","Unova Route 11 Area"], [], []],
  [588, 'white', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 11 Area"], [], []],
  [588, 'white', 'gen5-random', ["Unova Route 6 Area","Unova Route 11 Area"], [], []],
  [588, 'white2', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 11 Area"], [], []],
  [588, 'white2', 'gen5-random', ["Icirrus City Area","Unova Route 6 Area","Unova Route 8 Area","Moor Of Icirrus Area","Unova Route 11 Area"], [], []],
  [590, 'black', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [590, 'black', 'gen5-random', ["Unova Route 6 Area","Unova Route 7 Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [590, 'black', 'gen5-soft-reset', ["Unova Route 6 Area","Unova Route 10 Area"], [], []],
  [590, 'black2', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [590, 'black2', 'gen5-random', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [590, 'black2', 'gen5-soft-reset', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [590, 'white', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [590, 'white', 'gen5-random', ["Unova Route 6 Area","Unova Route 7 Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [590, 'white', 'gen5-soft-reset', ["Unova Route 6 Area","Unova Route 10 Area"], [], []],
  [590, 'white2', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [590, 'white2', 'gen5-random', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [590, 'white2', 'gen5-soft-reset', ["Unova Route 6 Area","Unova Route 7 Area"], [], []],
  [591, 'black', 'gen5-double-encounter', ["Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 11 Area"], [], []],
  [591, 'black', 'gen5-random', ["Unova Route 11 Area"], [], []],
  [591, 'black', 'gen5-soft-reset', ["Unova Route 10 Area"], [], []],
  [591, 'black2', 'gen5-double-encounter', ["Unova Route 11 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [591, 'black2', 'gen5-random', ["Unova Route 11 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [591, 'black2', 'gen5-soft-reset', ["Unova Route 11 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [591, 'white', 'gen5-double-encounter', ["Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 11 Area"], [], []],
  [591, 'white', 'gen5-random', ["Unova Route 11 Area"], [], []],
  [591, 'white', 'gen5-soft-reset', ["Unova Route 10 Area"], [], []],
  [591, 'white2', 'gen5-double-encounter', ["Unova Route 11 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [591, 'white2', 'gen5-random', ["Unova Route 11 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [591, 'white2', 'gen5-soft-reset', ["Unova Route 11 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [592, 'black', 'gen5-random', ["Driftveil City Area","P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area","Unova Route 17 Area"], [], []],
  [592, 'black2', 'gen5-random', ["P2 Laboratory Area","Undella Bay Area","Unova Route 4 Area","Unova Route 13 Area","Unova Route 18 Area","Undella Town Area","Unova Route 17 Area","Virbank City Area","Humilau City Area","Virbank Complex Outer","Seaside Cave 1f","Unova Route 21 Area"], [], []],
  [592, 'white', 'gen5-random', ["Driftveil City Area","P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area","Unova Route 17 Area"], [], []],
  [592, 'white2', 'gen5-random', ["P2 Laboratory Area","Undella Bay Area","Unova Route 4 Area","Unova Route 13 Area","Unova Route 18 Area","Undella Town Area","Unova Route 17 Area","Virbank City Area","Humilau City Area","Virbank Complex Outer","Seaside Cave 1f","Unova Route 21 Area"], [], []],
  [593, 'black', 'gen5-rippling-waters', ["Driftveil City Area","P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area","Unova Route 17 Area"], [], []],
  [593, 'black2', 'gen5-rippling-waters', ["P2 Laboratory Area","Undella Bay Area","Unova Route 4 Area","Unova Route 13 Area","Unova Route 18 Area","Undella Town Area","Unova Route 17 Area","Virbank City Area","Humilau City Area","Virbank Complex Outer","Seaside Cave 1f","Unova Route 21 Area"], [], []],
  [593, 'black2', 'gen5-soft-reset', ["Undella Bay Area"], [], []],
  [593, 'white', 'gen5-rippling-waters', ["Driftveil City Area","P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area","Unova Route 17 Area"], [], []],
  [593, 'white2', 'gen5-rippling-waters', ["P2 Laboratory Area","Undella Bay Area","Unova Route 4 Area","Unova Route 13 Area","Unova Route 18 Area","Undella Town Area","Unova Route 17 Area","Virbank City Area","Humilau City Area","Virbank Complex Outer","Seaside Cave 1f","Unova Route 21 Area"], [], []],
  [593, 'white2', 'gen5-soft-reset', ["Undella Bay Area"], [], []],
  [594, 'black', 'gen5-rippling-waters', ["Driftveil City Area","P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area","Unova Route 17 Area"], [], []],
  [594, 'black2', 'gen5-rippling-waters', ["P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area","Unova Route 17 Area","Virbank City Area","Virbank Complex Outer","Unova Route 21 Area"], [], []],
  [594, 'white', 'gen5-rippling-waters', ["Driftveil City Area","P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area","Unova Route 17 Area"], [], []],
  [594, 'white2', 'gen5-rippling-waters', ["P2 Laboratory Area","Unova Route 4 Area","Unova Route 18 Area","Unova Route 17 Area","Virbank City Area","Virbank Complex Outer","Unova Route 21 Area"], [], []],
  [595, 'black', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [595, 'black2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [595, 'white', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [595, 'white2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [597, 'black', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [597, 'black2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [597, 'white', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [597, 'white2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [599, 'black', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","P2 Laboratory Area"], [], []],
  [599, 'black2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [599, 'white', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","P2 Laboratory Area"], [], []],
  [599, 'white2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [600, 'black2', 'gen5-random', ["P2 Laboratory Area"], [], []],
  [600, 'white2', 'gen5-random', ["P2 Laboratory Area"], [], []],
  [601, 'black2', 'gen5-rustling-grass', ["P2 Laboratory Area"], [], []],
  [601, 'white2', 'gen5-rustling-grass', ["P2 Laboratory Area"], [], []],
  [602, 'black', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [602, 'black2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Seaside Cave 1f"], [], []],
  [602, 'white', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f"], [], []],
  [602, 'white2', 'gen5-random', ["Chargestone Cave 1f","Chargestone Cave B1f","Chargestone Cave B2f","Seaside Cave 1f"], [], []],
  [603, 'black2', 'gen5-random', ["Seaside Cave B1f"], [], []],
  [603, 'white2', 'gen5-random', ["Seaside Cave B1f"], [], []],
  [605, 'black', 'gen5-random', ["Celestial Tower 3f","Celestial Tower 4f","Celestial Tower 5f"], [], []],
  [605, 'black2', 'gen5-random', ["Celestial Tower 3f","Celestial Tower 4f","Celestial Tower 5f"], [], []],
  [605, 'white', 'gen5-random', ["Celestial Tower 3f","Celestial Tower 4f","Celestial Tower 5f"], [], []],
  [605, 'white2', 'gen5-random', ["Celestial Tower 3f","Celestial Tower 4f","Celestial Tower 5f"], [], []],
  [606, 'black', 'gen5-double-encounter', ["Unova Route 14 Area"], [], []],
  [606, 'black', 'gen5-random', ["Unova Route 14 Area"], [], []],
  [606, 'white', 'gen5-double-encounter', ["Unova Route 14 Area"], [], []],
  [606, 'white', 'gen5-random', ["Unova Route 14 Area"], [], []],
  [607, 'black', 'gen5-random', ["Celestial Tower 2f","Celestial Tower 3f","Celestial Tower 4f","Celestial Tower 5f"], [], []],
  [607, 'black2', 'gen5-random', ["Celestial Tower 2f","Celestial Tower 3f","Celestial Tower 4f","Celestial Tower 5f","Strange House 1f","Strange House B1f"], [], []],
  [607, 'white', 'gen5-random', ["Celestial Tower 2f","Celestial Tower 3f","Celestial Tower 4f","Celestial Tower 5f"], [], []],
  [607, 'white2', 'gen5-random', ["Celestial Tower 2f","Celestial Tower 3f","Celestial Tower 4f","Celestial Tower 5f","Strange House 1f","Strange House B1f"], [], []],
  [610, 'black', 'gen5-random', ["Mistralton Cave Area","Guidance Chamber Area"], [], []],
  [610, 'black2', 'gen5-random', ["Mistralton Cave Area","Guidance Chamber Area"], [], []],
  [610, 'white', 'gen5-random', ["Mistralton Cave Area","Guidance Chamber Area"], [], []],
  [610, 'white2', 'gen5-random', ["Mistralton Cave Area","Guidance Chamber Area"], [], []],
  [611, 'black', 'gen5-random', ["Unova Victory Road Outside"], [], []],
  [611, 'black2', 'gen5-double-encounter', ["Nature Sanctuary Area"], [], []],
  [611, 'black2', 'gen5-random', ["Nature Sanctuary Area"], [], []],
  [611, 'white', 'gen5-random', ["Unova Victory Road Outside"], [], []],
  [611, 'white2', 'gen5-double-encounter', ["Nature Sanctuary Area"], [], []],
  [611, 'white2', 'gen5-random', ["Nature Sanctuary Area"], [], []],
  [612, 'black2', 'gen5-guaranteed-shiny', ["Nature Sanctuary Area"], [], []],
  [612, 'white2', 'gen5-guaranteed-shiny', ["Nature Sanctuary Area"], [], []],
  [613, 'black', 'gen5-double-encounter', ["Unova Route 7 Area"], [], []],
  [613, 'black', 'gen5-random', ["Twist Mountain B1f 3f","Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 7 Area"], [], []],
  [613, 'black2', 'gen5-double-encounter', ["Unova Route 7 Area"], [], []],
  [613, 'black2', 'gen5-random', ["Unova Route 7 Area"], [], []],
  [613, 'white', 'gen5-double-encounter', ["Unova Route 7 Area"], [], []],
  [613, 'white', 'gen5-random', ["Twist Mountain B1f 3f","Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 7 Area"], [], []],
  [613, 'white2', 'gen5-double-encounter', ["Unova Route 7 Area"], [], []],
  [613, 'white2', 'gen5-random', ["Unova Route 7 Area"], [], []],
  [614, 'black', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [614, 'black2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [614, 'black2', 'gen5-random', ["Twist Mountain B1f 3f","Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [614, 'white', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [614, 'white2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [614, 'white2', 'gen5-random', ["Twist Mountain B1f 3f","Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [615, 'black', 'gen5-random', ["Twist Mountain B1f 3f"], [], []],
  [615, 'black2', 'gen5-random', ["Twist Mountain B1f 3f"], [], []],
  [615, 'white', 'gen5-random', ["Twist Mountain B1f 3f"], [], []],
  [615, 'white2', 'gen5-random', ["Twist Mountain B1f 3f"], [], []],
  [616, 'black', 'gen5-random', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [616, 'black2', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 11 Area"], [], []],
  [616, 'black2', 'gen5-random', ["Icirrus City Area","Unova Route 6 Area","Unova Route 8 Area","Moor Of Icirrus Area","Unova Route 11 Area"], [], []],
  [616, 'white', 'gen5-random', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [616, 'white2', 'gen5-double-encounter', ["Unova Route 6 Area","Unova Route 11 Area"], [], []],
  [616, 'white2', 'gen5-random', ["Icirrus City Area","Unova Route 6 Area","Unova Route 8 Area","Moor Of Icirrus Area","Unova Route 11 Area"], [], []],
  [618, 'black', 'gen5-random', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'black', 'gen5-rippling-waters', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'black', 'gen5-super-rod', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'black2', 'gen5-random', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'black2', 'gen5-rippling-waters', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'black2', 'gen5-super-rod', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'white', 'gen5-random', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'white', 'gen5-rippling-waters', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'white', 'gen5-super-rod', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'white2', 'gen5-random', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'white2', 'gen5-rippling-waters', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [618, 'white2', 'gen5-super-rod', ["Icirrus City Area","Unova Route 8 Area","Moor Of Icirrus Area"], [], []],
  [619, 'black', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [619, 'black', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Dragonspiral Tower 1f","Unova Victory Road Outside","Unova Victory Road Unknown Area 53","Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road 1f Unknown Room","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area","Unova Route 14 Area"], [], []],
  [619, 'black2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Unova Route 14 Area","Unova Route 22 Area"], [], []],
  [619, 'black2', 'gen5-random', ["Unova Route 14 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [619, 'white', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside"], [], []],
  [619, 'white', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Dragonspiral Tower 1f","Unova Victory Road Outside","Unova Victory Road Unknown Area 53","Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road 1f Unknown Room","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area","Unova Route 14 Area"], [], []],
  [619, 'white2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Unova Route 14 Area","Unova Route 22 Area"], [], []],
  [619, 'white2', 'gen5-random', ["Unova Route 14 Area","Unova Route 22 Area","Unova Route 23 Area"], [], []],
  [620, 'black', 'gen5-double-encounter', ["Unova Route 14 Area"], [], []],
  [620, 'black2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 23 Area"], [], []],
  [620, 'black2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Dragonspiral Tower 1f"], [], []],
  [620, 'white', 'gen5-double-encounter', ["Unova Route 14 Area"], [], []],
  [620, 'white2', 'gen5-double-encounter', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Unova Route 23 Area"], [], []],
  [620, 'white2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Dragonspiral Tower 1f"], [], []],
  [621, 'black', 'gen5-double-encounter', ["Dragonspiral Tower Outside"], [], []],
  [621, 'black', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Dragonspiral Tower 1f"], [], []],
  [621, 'black2', 'gen5-double-encounter', ["Dragonspiral Tower Outside"], [], []],
  [621, 'black2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Dragonspiral Tower 1f","Unova Victory Road 2 Unknown Area 77","Unova Victory Road 2 Unknown Area 80"], [], []],
  [621, 'white', 'gen5-double-encounter', ["Dragonspiral Tower Outside"], [], []],
  [621, 'white', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Dragonspiral Tower 1f"], [], []],
  [621, 'white2', 'gen5-double-encounter', ["Dragonspiral Tower Outside"], [], []],
  [621, 'white2', 'gen5-random', ["Dragonspiral Tower Entrance","Dragonspiral Tower Outside","Dragonspiral Tower 1f","Unova Victory Road 2 Unknown Area 77","Unova Victory Road 2 Unknown Area 80"], [], []],
  [622, 'black', 'gen5-random', ["Dragonspiral Tower 1f","Dragonspiral Tower 2f"], [], []],
  [622, 'white', 'gen5-random', ["Dragonspiral Tower 1f","Dragonspiral Tower 2f"], [], []],
  [623, 'black2', 'gen5-random', ["Dragonspiral Tower 1f","Dragonspiral Tower 2f","Unova Victory Road 2 Unknown Area 71","Unova Victory Road 2 Unknown Area 78"], [], []],
  [623, 'white2', 'gen5-random', ["Dragonspiral Tower 1f","Dragonspiral Tower 2f","Unova Victory Road 2 Unknown Area 71","Unova Victory Road 2 Unknown Area 78"], [], []],
  [624, 'black', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [624, 'black', 'gen5-random', ["Unova Route 9 Area","Unova Route 11 Area"], [], []],
  [624, 'black2', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [624, 'black2', 'gen5-random', ["Unova Route 9 Area"], [], []],
  [624, 'white', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [624, 'white', 'gen5-random', ["Unova Route 9 Area","Unova Route 11 Area"], [], []],
  [624, 'white2', 'gen5-double-encounter', ["Unova Route 9 Area"], [], []],
  [624, 'white2', 'gen5-random', ["Unova Route 9 Area"], [], []],
  [625, 'black', 'gen5-double-encounter', ["Unova Route 11 Area"], [], []],
  [625, 'white', 'gen5-double-encounter', ["Unova Route 11 Area"], [], []],
  [626, 'black', 'gen5-double-encounter', ["Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [626, 'black', 'gen5-random', ["Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [626, 'black2', 'gen5-double-encounter', ["Unova Route 23 Area"], [], []],
  [626, 'black2', 'gen5-random', ["Unova Route 23 Area"], [], []],
  [626, 'white', 'gen5-double-encounter', ["Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [626, 'white', 'gen5-random', ["Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [626, 'white2', 'gen5-double-encounter', ["Unova Route 23 Area"], [], []],
  [626, 'white2', 'gen5-random', ["Unova Route 23 Area"], [], []],
  [627, 'white', 'gen5-double-encounter', ["Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [627, 'white', 'gen5-random', ["Unova Victory Road Outside","Village Bridge Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 11 Area"], [], []],
  [627, 'white2', 'gen5-double-encounter', ["Unova Route 23 Area"], [], []],
  [627, 'white2', 'gen5-random', ["Unova Route 23 Area"], [], []],
  [628, 'white', 'gen5-double-encounter', ["Village Bridge Area","Unova Route 11 Area"], [], []],
  [628, 'white2', 'gen5-soft-reset', ["Unova Route 4 Area"], [], []],
  [629, 'black', 'gen5-double-encounter', ["Unova Route 10 Area","Unova Route 10 Victory Road Gate"], [], []],
  [629, 'black', 'gen5-random', ["Unova Victory Road Outside","Village Bridge Area","Unova Route 10 Area","Unova Route 10 Victory Road Gate","Unova Route 11 Area"], [], []],
  [629, 'black2', 'gen5-double-encounter', ["Unova Route 23 Area"], [], []],
  [629, 'black2', 'gen5-random', ["Unova Route 23 Area"], [], []],
  [630, 'black', 'gen5-double-encounter', ["Village Bridge Area","Unova Route 11 Area"], [], []],
  [630, 'black2', 'gen5-soft-reset', ["Unova Route 4 Area"], [], []],
  [631, 'black', 'gen5-random', ["Unova Victory Road Outside"], [], []],
  [631, 'black2', 'gen5-random', ["Twist Mountain B1f 3f"], [], []],
  [631, 'white', 'gen5-random', ["Unova Victory Road Outside"], [], []],
  [631, 'white2', 'gen5-random', ["Twist Mountain B1f 3f"], [], []],
  [632, 'black', 'gen5-random', ["Unova Victory Road Unknown Area 53","Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road 1f Unknown Room","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area"], [], []],
  [632, 'black2', 'gen5-random', ["Twist Mountain B1f 3f","Clay Tunnel Area","Underground Ruins Area","Rocky Mountain Room Area","Glacier Room Area","Iron Room Area"], [], []],
  [632, 'white', 'gen5-random', ["Unova Victory Road Unknown Area 53","Unova Victory Road Unknown Area 54","Unova Victory Road Unknown Area 55","Unova Victory Road 4f Middle Room","Unova Victory Road Unknown Area 57","Unova Victory Road 1f Unknown Room","Unova Victory Road Unknown Area 59","Unova Victory Road Unknown Area 60","Unova Victory Road Unknown Area 61","Unova Victory Road Unknown Area 62","Unova Victory Road Unknown Area 63","Unova Victory Road Unknown Area 64","Unova Victory Road Unknown Area 65","Unova Victory Road Unknown Area 66","Trial Chamber Area"], [], []],
  [632, 'white2', 'gen5-random', ["Twist Mountain B1f 3f","Clay Tunnel Area","Underground Ruins Area","Rocky Mountain Room Area","Glacier Room Area","Iron Room Area"], [], []],
  [633, 'black', 'gen5-random', ["Unova Victory Road Unknown Area 53","Unova Victory Road 1f Unknown Room"], [], []],
  [633, 'white', 'gen5-random', ["Unova Victory Road Unknown Area 53","Unova Victory Road 1f Unknown Room"], [], []],
  [634, 'black2', 'gen5-random', ["Unova Victory Road 2 Unknown Area 77","Unova Victory Road 2 Unknown Area 80"], [], []],
  [634, 'white2', 'gen5-random', ["Unova Victory Road 2 Unknown Area 77","Unova Victory Road 2 Unknown Area 80"], [], []],
  [636, 'black', 'gen5-gift', ["Unova Route 18 Area"], [], []],
  [636, 'white', 'gen5-gift', ["Unova Route 18 Area"], [], []],
  [637, 'black', 'gen5-soft-reset', ["Relic Castle D"], [], []],
  [637, 'black2', 'gen5-soft-reset', ["Relic Castle D"], [], []],
  [637, 'white', 'gen5-soft-reset', ["Relic Castle D"], [], []],
  [637, 'white2', 'gen5-soft-reset', ["Relic Castle D"], [], []],
  [638, 'black', 'gen5-soft-reset', ["Mistralton Cave Area"], [], []],
  [638, 'black2', 'gen5-soft-reset', ["Unova Route 13 Area"], [], []],
  [638, 'white', 'gen5-soft-reset', ["Mistralton Cave Area"], [], []],
  [638, 'white2', 'gen5-soft-reset', ["Unova Route 13 Area"], [], []],
  [639, 'black', 'gen5-soft-reset', ["Unova Victory Road 4f Middle Room"], [], []],
  [639, 'black2', 'gen5-soft-reset', ["Unova Route 22 Area"], [], []],
  [639, 'white', 'gen5-soft-reset', ["Unova Victory Road 4f Middle Room"], [], []],
  [639, 'white2', 'gen5-soft-reset', ["Unova Route 22 Area"], [], []],
  [640, 'black', 'gen5-soft-reset', ["Pinwheel Forest Rumination Field"], [], []],
  [640, 'black2', 'gen5-soft-reset', ["Unova Route 11 Area"], [], []],
  [640, 'white', 'gen5-soft-reset', ["Pinwheel Forest Rumination Field"], [], []],
  [640, 'white2', 'gen5-soft-reset', ["Unova Route 11 Area"], [], []],
  [641, 'black', 'gen5-soft-reset', ["Team Flare Secret Hq Area"], [], []],
  [642, 'white', 'gen5-soft-reset', ["Team Flare Secret Hq Area"], [], []],
  [643, 'black', 'gen5-soft-reset', ["Ns Castle Throne Room","Dragonspiral Tower 7f"], [], []],
  [643, 'white2', 'gen5-soft-reset', ["Dragonspiral Tower 7f"], [], []],
  [644, 'black2', 'gen5-soft-reset', ["Dragonspiral Tower 7f"], [], []],
  [644, 'white', 'gen5-soft-reset', ["Ns Castle Throne Room","Dragonspiral Tower 7f"], [], []],
  [645, 'black', 'gen5-soft-reset', ["Abundant Shrine Area"], [], []],
  [645, 'white', 'gen5-soft-reset', ["Abundant Shrine Area"], [], []],
  [646, 'black', 'gen5-soft-reset', ["Giant Chasm Forest Cave"], [], []],
  [646, 'black2', 'gen5-soft-reset', ["Giant Chasm Forest Cave"], [], []],
  [646, 'white', 'gen5-soft-reset', ["Giant Chasm Forest Cave"], [], []],
  [646, 'white2', 'gen5-soft-reset', ["Giant Chasm Forest Cave"], [], []],
] as const;
