export const trainerAvatars = [
  // Remote sprites hosted by Pokémon Showdown (no local assets needed).
  // NOTE: Many sprites are fan-made; credit/permissions may be required for reuse.
  { id: 'red', label: 'Red', src: 'https://play.pokemonshowdown.com/sprites/trainers/red.png' },
  { id: 'blue', label: 'Blue', src: 'https://play.pokemonshowdown.com/sprites/trainers/blue.png' },
  { id: 'ethan', label: 'Ethan', src: 'https://play.pokemonshowdown.com/sprites/trainers/ethan.png' },
  { id: 'lyra', label: 'Lyra', src: 'https://play.pokemonshowdown.com/sprites/trainers/lyra.png' },
  { id: 'brendan', label: 'Brendan', src: 'https://play.pokemonshowdown.com/sprites/trainers/brendan.png' },
  { id: 'may', label: 'May', src: 'https://play.pokemonshowdown.com/sprites/trainers/may.png' },
  { id: 'lucas', label: 'Lucas', src: 'https://play.pokemonshowdown.com/sprites/trainers/lucas.png' },
  { id: 'dawn', label: 'Dawn', src: 'https://play.pokemonshowdown.com/sprites/trainers/dawn.png' },
  { id: 'hilbert', label: 'Hilbert', src: 'https://play.pokemonshowdown.com/sprites/trainers/hilbert.png' },
  { id: 'hilda', label: 'Hilda', src: 'https://play.pokemonshowdown.com/sprites/trainers/hilda.png' },
  { id: 'calem', label: 'Calem', src: 'https://play.pokemonshowdown.com/sprites/trainers/calem.png' },
  { id: 'serena', label: 'Serena', src: 'https://play.pokemonshowdown.com/sprites/trainers/serena.png' },
  { id: 'leaf-gen3', label: 'Leaf', src: 'https://play.pokemonshowdown.com/sprites/trainers/leaf-gen3.png' },
  { id: 'kris-gen2', label: 'Kris', src: 'https://play.pokemonshowdown.com/sprites/trainers/kris-gen2.png' },
  { id: 'cynthia', label: 'Cynthia', src: 'https://play.pokemonshowdown.com/sprites/trainers/cynthia.png' },
  { id: 'silver', label: 'Silver', src: 'https://play.pokemonshowdown.com/sprites/trainers/silver.png' },
  { id: 'steven', label: 'Steven', src: 'https://play.pokemonshowdown.com/sprites/trainers/steven.png' },
  { id: 'iris', label: 'Iris', src: 'https://play.pokemonshowdown.com/sprites/trainers/iris.png' },
  { id: 'wally', label: 'Wally', src: 'https://play.pokemonshowdown.com/sprites/trainers/wally.png' },
  // Extras that are known to exist in the Showdown index.
  { id: 'misty', label: 'Misty', src: 'https://play.pokemonshowdown.com/sprites/trainers/misty.png' },
  { id: 'brock', label: 'Brock', src: 'https://play.pokemonshowdown.com/sprites/trainers/brock.png' },
  { id: 'n', label: 'N', src: 'https://play.pokemonshowdown.com/sprites/trainers/n.png' },
  { id: 'lance', label: 'Lance', src: 'https://play.pokemonshowdown.com/sprites/trainers/lance.png' },
  { id: 'lillie', label: 'Lillie', src: 'https://play.pokemonshowdown.com/sprites/trainers/lillie.png' },
  { id: 'marnie', label: 'Marnie', src: 'https://play.pokemonshowdown.com/sprites/trainers/marnie.png' },
  { id: 'black', label: 'Black', src: '/img/trainers/black.svg' },
  { id: 'diamond', label: 'Diamond', src: '/img/trainers/diamond.svg' },
  { id: 'emerald', label: 'Emerald', src: '/img/trainers/emerald.svg' },
  { id: 'gold', label: 'Gold', src: '/img/trainers/gold.svg' },
  { id: 'pearl', label: 'Pearl', src: '/img/trainers/pearl.svg' },
  { id: 'ruby', label: 'Ruby', src: '/img/trainers/ruby.svg' },
  { id: 'sapphire', label: 'Sapphire', src: '/img/trainers/sapphire.svg' },
  { id: 'scarlet', label: 'Scarlet', src: '/img/trainers/scarlet.svg' },
  { id: 'silver-gen2', label: 'Silver', src: '/img/trainers/silver.svg' },
  { id: 'violet', label: 'Violet', src: '/img/trainers/violet.svg' },
  { id: 'archer', label: 'Archer', src: 'https://play.pokemonshowdown.com/sprites/trainers/archer.png' },
  { id: 'bianca', label: 'Bianca', src: 'https://play.pokemonshowdown.com/sprites/trainers/bianca.png' },
  { id: 'cyrus', label: 'Cyrus', src: 'https://play.pokemonshowdown.com/sprites/trainers/cyrus.png' },
  { id: 'elio', label: 'Elio', src: 'https://play.pokemonshowdown.com/sprites/trainers/elio.png' },
  { id: 'gloria', label: 'Gloria', src: 'https://play.pokemonshowdown.com/sprites/trainers/gloria.png' },
  { id: 'arven', label: 'Arven', src: 'https://play.pokemonshowdown.com/sprites/trainers/arven.png' },
  { id: 'bede', label: 'Bede', src: 'https://play.pokemonshowdown.com/sprites/trainers/bede.png' },
  { id: 'hop', label: 'Hop', src: 'https://play.pokemonshowdown.com/sprites/trainers/hop.png' },
  { id: 'nemona', label: 'Nemona', src: 'https://play.pokemonshowdown.com/sprites/trainers/nemona.png' },
  { id: 'penny', label: 'Penny', src: 'https://play.pokemonshowdown.com/sprites/trainers/penny.png' },
] as const;
