export const trainerAvatars = [
  // Remote sprites hosted by Pokemon Showdown (no local assets needed).
  // NOTE: Many sprites are fan-made; credit/permissions may be required for reuse.
  // Playable main-game characters, ordered male/female by generation.
  { id: 'red', label: 'Red', src: 'https://play.pokemonshowdown.com/sprites/trainers/red.png' },
  { id: 'leaf-gen3', label: 'Leaf', src: 'https://play.pokemonshowdown.com/sprites/trainers/leaf-gen3.png' },
  { id: 'chase', label: 'Chase', src: 'https://play.pokemonshowdown.com/sprites/trainers/chase.png' },
  { id: 'elaine', label: 'Elaine', src: 'https://play.pokemonshowdown.com/sprites/trainers/elaine.png' },
  { id: 'ethan', label: 'Ethan', src: 'https://play.pokemonshowdown.com/sprites/trainers/ethan.png' },
  { id: 'kris', label: 'Kris', src: 'https://play.pokemonshowdown.com/sprites/trainers/kris.png' },
  { id: 'lyra', label: 'Lyra', src: 'https://play.pokemonshowdown.com/sprites/trainers/lyra.png' },
  { id: 'brendan', label: 'Brendan', src: 'https://play.pokemonshowdown.com/sprites/trainers/brendan.png' },
  { id: 'may', label: 'May', src: 'https://play.pokemonshowdown.com/sprites/trainers/may.png' },
  { id: 'lucas', label: 'Lucas', src: 'https://play.pokemonshowdown.com/sprites/trainers/lucas.png' },
  { id: 'dawn', label: 'Dawn', src: 'https://play.pokemonshowdown.com/sprites/trainers/dawn.png' },
  { id: 'hilbert', label: 'Hilbert', src: 'https://play.pokemonshowdown.com/sprites/trainers/hilbert.png' },
  { id: 'hilda', label: 'Hilda', src: 'https://play.pokemonshowdown.com/sprites/trainers/hilda.png' },
  { id: 'nate', label: 'Nate', src: 'https://play.pokemonshowdown.com/sprites/trainers/nate.png' },
  { id: 'rosa', label: 'Rosa', src: 'https://play.pokemonshowdown.com/sprites/trainers/rosa.png' },
  { id: 'calem', label: 'Calem', src: 'https://play.pokemonshowdown.com/sprites/trainers/calem.png' },
  { id: 'serena', label: 'Serena', src: 'https://play.pokemonshowdown.com/sprites/trainers/serena.png' },
  { id: 'elio', label: 'Elio', src: 'https://play.pokemonshowdown.com/sprites/trainers/elio.png' },
  { id: 'selene', label: 'Selene', src: 'https://play.pokemonshowdown.com/sprites/trainers/selene.png' },
  { id: 'victor', label: 'Victor', src: 'https://play.pokemonshowdown.com/sprites/trainers/victor.png' },
  { id: 'gloria', label: 'Gloria', src: 'https://play.pokemonshowdown.com/sprites/trainers/gloria.png' },
  { id: 'rei', label: 'Rei', src: 'https://play.pokemonshowdown.com/sprites/trainers/rei.png' },
  { id: 'akari', label: 'Akari', src: 'https://play.pokemonshowdown.com/sprites/trainers/akari.png' },
  { id: 'florian-s', label: 'Florian', src: 'https://play.pokemonshowdown.com/sprites/trainers/florian-s.png' },
  { id: 'juliana-s', label: 'Juliana', src: 'https://play.pokemonshowdown.com/sprites/trainers/juliana-s.png' },
  // Other major characters, ordered by debut generation.
  { id: 'blue', label: 'Blue', src: 'https://play.pokemonshowdown.com/sprites/trainers/blue.png' },
  { id: 'oak', label: 'Oak', src: 'https://play.pokemonshowdown.com/sprites/trainers/oak.png' },
  { id: 'ash', label: 'Ash', src: 'https://play.pokemonshowdown.com/sprites/trainers/ash.png' },
  { id: 'brock', label: 'Brock', src: 'https://play.pokemonshowdown.com/sprites/trainers/brock.png' },
  { id: 'misty', label: 'Misty', src: 'https://play.pokemonshowdown.com/sprites/trainers/misty.png' },
  { id: 'ltsurge', label: 'Lt. Surge', src: 'https://play.pokemonshowdown.com/sprites/trainers/ltsurge.png' },
  { id: 'erika', label: 'Erika', src: 'https://play.pokemonshowdown.com/sprites/trainers/erika.png' },
  { id: 'sabrina', label: 'Sabrina', src: 'https://play.pokemonshowdown.com/sprites/trainers/sabrina.png' },
  { id: 'koga', label: 'Koga', src: 'https://play.pokemonshowdown.com/sprites/trainers/koga.png' },
  { id: 'blaine', label: 'Blaine', src: 'https://play.pokemonshowdown.com/sprites/trainers/blaine.png' },
  { id: 'giovanni', label: 'Giovanni', src: 'https://play.pokemonshowdown.com/sprites/trainers/giovanni.png' },
  { id: 'lorelei-gen3', label: 'Lorelei', src: 'https://play.pokemonshowdown.com/sprites/trainers/lorelei-gen3.png' },
  { id: 'bruno', label: 'Bruno', src: 'https://play.pokemonshowdown.com/sprites/trainers/bruno.png' },
  { id: 'agatha-gen3', label: 'Agatha', src: 'https://play.pokemonshowdown.com/sprites/trainers/agatha-gen3.png' },
  { id: 'lance', label: 'Lance', src: 'https://play.pokemonshowdown.com/sprites/trainers/lance.png' },
  { id: 'silver', label: 'Silver', src: 'https://play.pokemonshowdown.com/sprites/trainers/silver.png' },
  { id: 'falkner', label: 'Falkner', src: 'https://play.pokemonshowdown.com/sprites/trainers/falkner.png' },
  { id: 'bugsy', label: 'Bugsy', src: 'https://play.pokemonshowdown.com/sprites/trainers/bugsy.png' },
  { id: 'whitney', label: 'Whitney', src: 'https://play.pokemonshowdown.com/sprites/trainers/whitney.png' },
  { id: 'morty', label: 'Morty', src: 'https://play.pokemonshowdown.com/sprites/trainers/morty.png' },
  { id: 'chuck', label: 'Chuck', src: 'https://play.pokemonshowdown.com/sprites/trainers/chuck.png' },
  { id: 'jasmine', label: 'Jasmine', src: 'https://play.pokemonshowdown.com/sprites/trainers/jasmine.png' },
  { id: 'pryce', label: 'Pryce', src: 'https://play.pokemonshowdown.com/sprites/trainers/pryce.png' },
  { id: 'clair', label: 'Clair', src: 'https://play.pokemonshowdown.com/sprites/trainers/clair.png' },
  { id: 'janine', label: 'Janine', src: 'https://play.pokemonshowdown.com/sprites/trainers/janine.png', imageTransform: 'translate(-5%, 3%) scale(1.22)', imageTransformOrigin: 'center center' },
  { id: 'archer', label: 'Archer', src: 'https://play.pokemonshowdown.com/sprites/trainers/archer.png' },
  { id: 'ariana', label: 'Ariana', src: 'https://play.pokemonshowdown.com/sprites/trainers/ariana.png' },
  { id: 'wally', label: 'Wally', src: 'https://play.pokemonshowdown.com/sprites/trainers/wally.png' },
  { id: 'roxanne', label: 'Roxanne', src: 'https://play.pokemonshowdown.com/sprites/trainers/roxanne.png' },
  { id: 'brawly', label: 'Brawly', src: 'https://play.pokemonshowdown.com/sprites/trainers/brawly.png' },
  { id: 'wattson', label: 'Wattson', src: 'https://play.pokemonshowdown.com/sprites/trainers/wattson.png' },
  { id: 'flannery', label: 'Flannery', src: 'https://play.pokemonshowdown.com/sprites/trainers/flannery.png', imageTransform: 'translate(-7%, 2%) scale(1.18)', imageTransformOrigin: 'center center' },
  { id: 'norman', label: 'Norman', src: 'https://play.pokemonshowdown.com/sprites/trainers/norman.png' },
  { id: 'winona', label: 'Winona', src: 'https://play.pokemonshowdown.com/sprites/trainers/winona.png' },
  { id: 'tateandliza-gen6', label: 'Tate & Liza', src: 'https://play.pokemonshowdown.com/sprites/trainers/tateandliza-gen6.png' },
  { id: 'wallace', label: 'Wallace', src: 'https://play.pokemonshowdown.com/sprites/trainers/wallace.png', imageTransform: 'translateY(2%) scale(1.2)', imageTransformOrigin: 'center center' },
  { id: 'juan', label: 'Juan', src: 'https://play.pokemonshowdown.com/sprites/trainers/juan.png' },
  { id: 'phoebe-gen6', label: 'Phoebe', src: 'https://play.pokemonshowdown.com/sprites/trainers/phoebe-gen6.png' },
  { id: 'glacia', label: 'Glacia', src: 'https://play.pokemonshowdown.com/sprites/trainers/glacia.png' },
  { id: 'steven', label: 'Steven', src: 'https://play.pokemonshowdown.com/sprites/trainers/steven.png' },
  { id: 'archie-gen6', label: 'Archie', src: 'https://play.pokemonshowdown.com/sprites/trainers/archie-gen6.png' },
  { id: 'maxie-gen6', label: 'Maxie', src: 'https://play.pokemonshowdown.com/sprites/trainers/maxie-gen6.png' },
  { id: 'anabel', label: 'Anabel', src: 'https://play.pokemonshowdown.com/sprites/trainers/anabel.png' },
  { id: 'barry', label: 'Barry', src: 'https://play.pokemonshowdown.com/sprites/trainers/barry.png' },
  { id: 'roark', label: 'Roark', src: 'https://play.pokemonshowdown.com/sprites/trainers/roark.png' },
  { id: 'gardenia', label: 'Gardenia', src: 'https://play.pokemonshowdown.com/sprites/trainers/gardenia.png' },
  { id: 'maylene', label: 'Maylene', src: 'https://play.pokemonshowdown.com/sprites/trainers/maylene.png', imageTransform: 'translateY(3%) scale(1.28)', imageTransformOrigin: 'center center' },
  { id: 'crasherwake', label: 'Crasher Wake', src: 'https://play.pokemonshowdown.com/sprites/trainers/crasherwake.png' },
  { id: 'fantina', label: 'Fantina', src: 'https://play.pokemonshowdown.com/sprites/trainers/fantina.png' },
  { id: 'byron', label: 'Byron', src: 'https://play.pokemonshowdown.com/sprites/trainers/byron.png' },
  { id: 'candice', label: 'Candice', src: 'https://play.pokemonshowdown.com/sprites/trainers/candice.png' },
  { id: 'volkner', label: 'Volkner', src: 'https://play.pokemonshowdown.com/sprites/trainers/volkner.png' },
  { id: 'aaron', label: 'Aaron', src: 'https://play.pokemonshowdown.com/sprites/trainers/aaron.png' },
  { id: 'bertha', label: 'Bertha', src: 'https://play.pokemonshowdown.com/sprites/trainers/bertha.png', imageTransform: 'translateY(4%) scale(1.3)', imageTransformOrigin: 'center center' },
  { id: 'flint', label: 'Flint', src: 'https://play.pokemonshowdown.com/sprites/trainers/flint.png' },
  { id: 'lucian', label: 'Lucian', src: 'https://play.pokemonshowdown.com/sprites/trainers/lucian.png' },
  { id: 'cynthia', label: 'Cynthia', src: 'https://play.pokemonshowdown.com/sprites/trainers/cynthia.png' },
  { id: 'cyrus', label: 'Cyrus', src: 'https://play.pokemonshowdown.com/sprites/trainers/cyrus.png' },
  { id: 'marley', label: 'Marley', src: 'https://play.pokemonshowdown.com/sprites/trainers/marley.png' },
  { id: 'caitlin', label: 'Caitlin', src: 'https://play.pokemonshowdown.com/sprites/trainers/caitlin.png' },
  { id: 'cheren', label: 'Cheren', src: 'https://play.pokemonshowdown.com/sprites/trainers/cheren.png' },
  { id: 'bianca', label: 'Bianca', src: 'https://play.pokemonshowdown.com/sprites/trainers/bianca.png' },
  { id: 'n', label: 'N', src: 'https://play.pokemonshowdown.com/sprites/trainers/n.png' },
  { id: 'lenora', label: 'Lenora', src: 'https://play.pokemonshowdown.com/sprites/trainers/lenora.png' },
  { id: 'burgh', label: 'Burgh', src: 'https://play.pokemonshowdown.com/sprites/trainers/burgh.png', imageTransform: 'translate(-2%, 4%) scale(1.26)', imageTransformOrigin: 'center center' },
  { id: 'elesa', label: 'Elesa', src: 'https://play.pokemonshowdown.com/sprites/trainers/elesa.png', imageTransform: 'translate(-8%, 6%) scale(1.14)', imageTransformOrigin: 'center center' },
  { id: 'clay', label: 'Clay', src: 'https://play.pokemonshowdown.com/sprites/trainers/clay.png' },
  { id: 'skyla', label: 'Skyla', src: 'https://play.pokemonshowdown.com/sprites/trainers/skyla.png' },
  { id: 'drayden', label: 'Drayden', src: 'https://play.pokemonshowdown.com/sprites/trainers/drayden.png' },
  { id: 'roxie', label: 'Roxie', src: 'https://play.pokemonshowdown.com/sprites/trainers/roxie.png' },
  { id: 'marlon', label: 'Marlon', src: 'https://play.pokemonshowdown.com/sprites/trainers/marlon.png' },
  { id: 'shauntal', label: 'Shauntal', src: 'https://play.pokemonshowdown.com/sprites/trainers/shauntal.png', imageTransform: 'translateY(4%) scale(1.36)', imageTransformOrigin: 'center center' },
  { id: 'grimsley', label: 'Grimsley', src: 'https://play.pokemonshowdown.com/sprites/trainers/grimsley.png' },
  { id: 'marshal', label: 'Marshal', src: 'https://play.pokemonshowdown.com/sprites/trainers/marshal.png' },
  { id: 'iris', label: 'Iris', src: 'https://play.pokemonshowdown.com/sprites/trainers/iris.png', imageTransform: 'translateY(3%) scale(1.28)', imageTransformOrigin: 'center center' },
  { id: 'alder', label: 'Alder', src: 'https://play.pokemonshowdown.com/sprites/trainers/alder.png', imageTransform: 'translateY(5%) scale(1.16)', imageTransformOrigin: 'center center' },
  { id: 'ghetsis', label: 'Ghetsis', src: 'https://play.pokemonshowdown.com/sprites/trainers/ghetsis.png' },
  { id: 'colress', label: 'Colress', src: 'https://play.pokemonshowdown.com/sprites/trainers/colress.png' },
  { id: 'viola', label: 'Viola', src: 'https://play.pokemonshowdown.com/sprites/trainers/viola.png' },
  { id: 'grant', label: 'Grant', src: 'https://play.pokemonshowdown.com/sprites/trainers/grant.png' },
  { id: 'korrina', label: 'Korrina', src: 'https://play.pokemonshowdown.com/sprites/trainers/korrina.png' },
  { id: 'clemont', label: 'Clemont', src: 'https://play.pokemonshowdown.com/sprites/trainers/clemont.png' },
  { id: 'valerie', label: 'Valerie', src: 'https://play.pokemonshowdown.com/sprites/trainers/valerie.png' },
  { id: 'olympia', label: 'Olympia', src: 'https://play.pokemonshowdown.com/sprites/trainers/olympia.png' },
  { id: 'wulfric', label: 'Wulfric', src: 'https://play.pokemonshowdown.com/sprites/trainers/wulfric.png' },
  { id: 'malva', label: 'Malva', src: 'https://play.pokemonshowdown.com/sprites/trainers/malva.png' },
  { id: 'siebold', label: 'Siebold', src: 'https://play.pokemonshowdown.com/sprites/trainers/siebold.png' },
  { id: 'wikstrom', label: 'Wikstrom', src: 'https://play.pokemonshowdown.com/sprites/trainers/wikstrom.png' },
  { id: 'diantha', label: 'Diantha', src: 'https://play.pokemonshowdown.com/sprites/trainers/diantha.png' },
  { id: 'sycamore', label: 'Sycamore', src: 'https://play.pokemonshowdown.com/sprites/trainers/sycamore.png' },
  { id: 'lysandre', label: 'Lysandre', src: 'https://play.pokemonshowdown.com/sprites/trainers/lysandre.png' },
  { id: 'az', label: 'AZ', src: 'https://play.pokemonshowdown.com/sprites/trainers/az.png' },
  { id: 'hau', label: 'Hau', src: 'https://play.pokemonshowdown.com/sprites/trainers/hau.png' },
  { id: 'lillie', label: 'Lillie', src: 'https://play.pokemonshowdown.com/sprites/trainers/lillie.png' },
  { id: 'gladion', label: 'Gladion', src: 'https://play.pokemonshowdown.com/sprites/trainers/gladion.png' },
  { id: 'lusamine', label: 'Lusamine', src: 'https://play.pokemonshowdown.com/sprites/trainers/lusamine.png' },
  { id: 'guzma', label: 'Guzma', src: 'https://play.pokemonshowdown.com/sprites/trainers/guzma.png', imageTransform: 'translateY(3%) scale(1.28)', imageTransformOrigin: 'center center' },
  { id: 'plumeria', label: 'Plumeria', src: 'https://play.pokemonshowdown.com/sprites/trainers/plumeria.png' },
  { id: 'hala', label: 'Hala', src: 'https://play.pokemonshowdown.com/sprites/trainers/hala.png' },
  { id: 'olivia', label: 'Olivia', src: 'https://play.pokemonshowdown.com/sprites/trainers/olivia.png' },
  { id: 'acerola', label: 'Acerola', src: 'https://play.pokemonshowdown.com/sprites/trainers/acerola.png' },
  { id: 'mallow', label: 'Mallow', src: 'https://play.pokemonshowdown.com/sprites/trainers/mallow.png' },
  { id: 'kiawe', label: 'Kiawe', src: 'https://play.pokemonshowdown.com/sprites/trainers/kiawe.png' },
  { id: 'sophocles', label: 'Sophocles', src: 'https://play.pokemonshowdown.com/sprites/trainers/sophocles.png' },
  { id: 'kahili', label: 'Kahili', src: 'https://play.pokemonshowdown.com/sprites/trainers/kahili.png' },
  { id: 'hapu', label: 'Hapu', src: 'https://play.pokemonshowdown.com/sprites/trainers/hapu.png' },
  { id: 'kukui', label: 'Kukui', src: 'https://play.pokemonshowdown.com/sprites/trainers/kukui.png' },
  { id: 'hop', label: 'Hop', src: 'https://play.pokemonshowdown.com/sprites/trainers/hop.png' },
  { id: 'marnie', label: 'Marnie', src: 'https://play.pokemonshowdown.com/sprites/trainers/marnie.png' },
  { id: 'bede', label: 'Bede', src: 'https://play.pokemonshowdown.com/sprites/trainers/bede.png' },
  { id: 'leon', label: 'Leon', src: 'https://play.pokemonshowdown.com/sprites/trainers/leon.png' },
  { id: 'sonia', label: 'Sonia', src: 'https://play.pokemonshowdown.com/sprites/trainers/sonia.png' },
  { id: 'milo', label: 'Milo', src: 'https://play.pokemonshowdown.com/sprites/trainers/milo.png' },
  { id: 'nessa', label: 'Nessa', src: 'https://play.pokemonshowdown.com/sprites/trainers/nessa.png' },
  { id: 'kabu', label: 'Kabu', src: 'https://play.pokemonshowdown.com/sprites/trainers/kabu.png' },
  { id: 'bea', label: 'Bea', src: 'https://play.pokemonshowdown.com/sprites/trainers/bea.png' },
  { id: 'allister', label: 'Allister', src: 'https://play.pokemonshowdown.com/sprites/trainers/allister.png' },
  { id: 'opal', label: 'Opal', src: 'https://play.pokemonshowdown.com/sprites/trainers/opal.png' },
  { id: 'piers', label: 'Piers', src: 'https://play.pokemonshowdown.com/sprites/trainers/piers.png' },
  { id: 'raihan', label: 'Raihan', src: 'https://play.pokemonshowdown.com/sprites/trainers/raihan.png' },
  { id: 'rose', label: 'Rose', src: 'https://play.pokemonshowdown.com/sprites/trainers/rose.png' },
  { id: 'oleana', label: 'Oleana', src: 'https://play.pokemonshowdown.com/sprites/trainers/oleana.png' },
  { id: 'ballguy', label: 'Ball Guy', src: 'https://play.pokemonshowdown.com/sprites/trainers/ballguy.png' },
  { id: 'klara', label: 'Klara', src: 'https://play.pokemonshowdown.com/sprites/trainers/klara.png' },
  { id: 'avery', label: 'Avery', src: 'https://play.pokemonshowdown.com/sprites/trainers/avery.png' },
  { id: 'adaman', label: 'Adaman', src: 'https://play.pokemonshowdown.com/sprites/trainers/adaman.png' },
  { id: 'arezu', label: 'Arezu', src: 'https://play.pokemonshowdown.com/sprites/trainers/arezu.png' },
  { id: 'clavell-s', label: 'Clavell', src: 'https://play.pokemonshowdown.com/sprites/trainers/clavell-s.png' },
  { id: 'nemona-s', label: 'Nemona', src: 'https://play.pokemonshowdown.com/sprites/trainers/nemona-s.png' },
  { id: 'arven-s', label: 'Arven', src: 'https://play.pokemonshowdown.com/sprites/trainers/arven-s.png' },
  { id: 'penny', label: 'Penny', src: 'https://play.pokemonshowdown.com/sprites/trainers/penny.png' },
  { id: 'katy', label: 'Katy', src: 'https://play.pokemonshowdown.com/sprites/trainers/katy.png' },
  { id: 'brassius', label: 'Brassius', src: 'https://play.pokemonshowdown.com/sprites/trainers/brassius.png' },
  { id: 'iono', label: 'Iono', src: 'https://play.pokemonshowdown.com/sprites/trainers/iono.png' },
  { id: 'kofu', label: 'Kofu', src: 'https://play.pokemonshowdown.com/sprites/trainers/kofu.png' },
  { id: 'larry', label: 'Larry', src: 'https://play.pokemonshowdown.com/sprites/trainers/larry.png' },
  { id: 'tulip', label: 'Tulip', src: 'https://play.pokemonshowdown.com/sprites/trainers/tulip.png' },
  { id: 'grusha', label: 'Grusha', src: 'https://play.pokemonshowdown.com/sprites/trainers/grusha.png' },
  { id: 'rika', label: 'Rika', src: 'https://play.pokemonshowdown.com/sprites/trainers/rika.png' },
  { id: 'geeta', label: 'Geeta', src: 'https://play.pokemonshowdown.com/sprites/trainers/geeta.png' },
  { id: 'sada', label: 'Sada', src: 'https://play.pokemonshowdown.com/sprites/trainers/sada.png' },
  { id: 'carmine', label: 'Carmine', src: 'https://play.pokemonshowdown.com/sprites/trainers/carmine.png' },
  { id: 'amarys', label: 'Amarys', src: 'https://play.pokemonshowdown.com/sprites/trainers/amarys.png' },
] as const;
