export const trainerAvatars = [
  // Remote sprites hosted by Pokémon Showdown (no local assets needed).
  // NOTE: Many sprites are fan-made; credit/permissions may be required for reuse.
  { id: 'red', label: 'Red', src: 'https://play.pokemonshowdown.com/sprites/trainers/red.png' },
  { id: 'blue', label: 'Blue', src: 'https://play.pokemonshowdown.com/sprites/trainers/blue.png' },
  { id: 'ethan', label: 'Ethan', src: 'https://play.pokemonshowdown.com/sprites/trainers/ethan.png' },
  { id: 'lyra', label: 'Lyra', src: 'https://play.pokemonshowdown.com/sprites/trainers/lyra.png' },
  { id: 'brendan', label: 'Brendan', src: 'https://play.pokemonshowdown.com/sprites/trainers/brendan.png' },
  { id: 'may', label: 'May', src: 'https://play.pokemonshowdown.com/sprites/trainers/may.png' },
  { id: 'lucas', label: 'Lucas', src: 'https://play.pokemonshowdown.com/sprites/trainers/lucas.png' },
  { id: 'dawn', label: 'Dawn', src: 'https://play.pokemonshowdown.com/sprites/trainers/dawn.png' },
  { id: 'hilbert', label: 'Hilbert', src: 'https://play.pokemonshowdown.com/sprites/trainers/hilbert.png' },
  { id: 'hilda', label: 'Hilda', src: 'https://play.pokemonshowdown.com/sprites/trainers/hilda.png' },
  { id: 'calem', label: 'Calem', src: 'https://play.pokemonshowdown.com/sprites/trainers/calem.png' },
  { id: 'serena', label: 'Serena', src: 'https://play.pokemonshowdown.com/sprites/trainers/serena.png' },
  { id: 'leaf-gen3', label: 'Leaf', src: 'https://play.pokemonshowdown.com/sprites/trainers/leaf-gen3.png' },
  { id: 'volkner', label: 'Volkner', src: 'https://play.pokemonshowdown.com/sprites/trainers/volkner.png' },
  { id: 'cynthia', label: 'Cynthia', src: 'https://play.pokemonshowdown.com/sprites/trainers/cynthia.png' },
  { id: 'silver', label: 'Silver', src: 'https://play.pokemonshowdown.com/sprites/trainers/silver.png' },
  { id: 'steven', label: 'Steven', src: 'https://play.pokemonshowdown.com/sprites/trainers/steven.png' },
  { id: 'iris', label: 'Iris', src: 'https://play.pokemonshowdown.com/sprites/trainers/iris.png' },
  { id: 'wally', label: 'Wally', src: 'https://play.pokemonshowdown.com/sprites/trainers/wally.png' },
  // Extras that are known to exist in the Showdown index.
  { id: 'misty', label: 'Misty', src: 'https://play.pokemonshowdown.com/sprites/trainers/misty.png' },
  { id: 'brock', label: 'Brock', src: 'https://play.pokemonshowdown.com/sprites/trainers/brock.png' },
  { id: 'n', label: 'N', src: 'https://play.pokemonshowdown.com/sprites/trainers/n.png' },
  { id: 'lance', label: 'Lance', src: 'https://play.pokemonshowdown.com/sprites/trainers/lance.png' },
  { id: 'lillie', label: 'Lillie', src: 'https://play.pokemonshowdown.com/sprites/trainers/lillie.png' },
  { id: 'marnie', label: 'Marnie', src: 'https://play.pokemonshowdown.com/sprites/trainers/marnie.png' },
  { id: 'guzma', label: 'Guzma', src: 'https://play.pokemonshowdown.com/sprites/trainers/guzma.png' },
  { id: 'oak', label: 'Oak', src: 'https://play.pokemonshowdown.com/sprites/trainers/oak.png' },
  { id: 'alder', label: 'Alder', src: 'https://play.pokemonshowdown.com/sprites/trainers/alder.png' },
  { id: 'az', label: 'AZ', src: 'https://play.pokemonshowdown.com/sprites/trainers/az.png' },
  { id: 'caitlin', label: 'Caitlin', src: 'https://play.pokemonshowdown.com/sprites/trainers/caitlin.png' },
  { id: 'candice', label: 'Candice', src: 'https://play.pokemonshowdown.com/sprites/trainers/candice.png' },
  { id: 'archie-gen6', label: 'Archie', src: 'https://play.pokemonshowdown.com/sprites/trainers/archie-gen6.png' },
  { id: 'barry', label: 'Barry', src: 'https://play.pokemonshowdown.com/sprites/trainers/barry.png' },
  { id: 'bianca', label: 'Bianca', src: 'https://play.pokemonshowdown.com/sprites/trainers/bianca.png' },
  { id: 'bede', label: 'Bede', src: 'https://play.pokemonshowdown.com/sprites/trainers/bede.png' },
  { id: 'ghetsis', label: 'Ghetsis', src: 'https://play.pokemonshowdown.com/sprites/trainers/ghetsis.png' },
  { id: 'cheren', label: 'Cheren', src: 'https://play.pokemonshowdown.com/sprites/trainers/cheren.png' },
  { id: 'diantha', label: 'Diantha', src: 'https://play.pokemonshowdown.com/sprites/trainers/diantha.png' },
  { id: 'florian-s', label: 'Florian', src: 'https://play.pokemonshowdown.com/sprites/trainers/florian-s.png' },
  { id: 'cyrus', label: 'Cyrus', src: 'https://play.pokemonshowdown.com/sprites/trainers/cyrus.png' },
  { id: 'elio', label: 'Elio', src: 'https://play.pokemonshowdown.com/sprites/trainers/elio.png' },
  { id: 'gloria', label: 'Gloria', src: 'https://play.pokemonshowdown.com/sprites/trainers/gloria.png' },
  { id: 'leon', label: 'Leon', src: 'https://play.pokemonshowdown.com/sprites/trainers/leon.png' },
  { id: 'bede', label: 'Bede', src: 'https://play.pokemonshowdown.com/sprites/trainers/bede.png' },
  { id: 'hop', label: 'Hop', src: 'https://play.pokemonshowdown.com/sprites/trainers/hop.png' },
  { id: 'ballguy', label: 'Ball Guy', src: 'https://play.pokemonshowdown.com/sprites/trainers/ballguy.png' },
  { id: 'penny', label: 'Penny', src: 'https://play.pokemonshowdown.com/sprites/trainers/penny.png' },
  { id: 'marley', label: 'Marley', src: 'https://play.pokemonshowdown.com/sprites/trainers/marley.png' },
  { id: 'nate', label: 'Nate', src: 'https://play.pokemonshowdown.com/sprites/trainers/nate.png' },
  { id: 'rosa', label: 'Rosa', src: 'https://play.pokemonshowdown.com/sprites/trainers/rosa.png' },
] as const;
