ALTER TABLE public.active_hunts
ADD COLUMN IF NOT EXISTS pokemon_2_id INTEGER,
ADD COLUMN IF NOT EXISTS pokemon_2_name TEXT,
ADD COLUMN IF NOT EXISTS pokemon_3_id INTEGER,
ADD COLUMN IF NOT EXISTS pokemon_3_name TEXT,
ADD COLUMN IF NOT EXISTS pokemon_2_form TEXT,
ADD COLUMN IF NOT EXISTS pokemon_3_form TEXT,
ADD COLUMN IF NOT EXISTS pokemon_2_gender TEXT,
ADD COLUMN IF NOT EXISTS pokemon_3_gender TEXT;
