ALTER TABLE public.active_hunts
ADD COLUMN IF NOT EXISTS pokemon_2_id INTEGER,
ADD COLUMN IF NOT EXISTS pokemon_2_name TEXT,
ADD COLUMN IF NOT EXISTS pokemon_3_id INTEGER,
ADD COLUMN IF NOT EXISTS pokemon_3_name TEXT;
