// Generated by scripts/import-gen7-additional-sprites.mjs.
export const GEN7_ADDITIONAL_SHINY_SPRITE_ENTRIES = [
  {
    "file": "araquanid.webp",
    "source": "araquanid.gif",
    "speciesId": 752,
    "canonicalName": "araquanid",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "bewear.webp",
    "source": "bewear.gif",
    "speciesId": 760,
    "canonicalName": "bewear",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "blacephalon-usum.webp",
    "source": "Blacephalon_usum.webp",
    "speciesId": 806,
    "canonicalName": "blacephalon",
    "games": [
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "bounsweet.webp",
    "source": "bounsweet.gif",
    "speciesId": 761,
    "canonicalName": "bounsweet",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "brionne.webp",
    "source": "brionne.gif",
    "speciesId": 729,
    "canonicalName": "brionne",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "bruxish.webp",
    "source": "bruxish.gif",
    "speciesId": 779,
    "canonicalName": "bruxish",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "buzzwole.webp",
    "source": "buzzwole.gif",
    "speciesId": 794,
    "canonicalName": "buzzwole",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "celesteela.webp",
    "source": "celesteela.gif",
    "speciesId": 797,
    "canonicalName": "celesteela",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "charjabug.webp",
    "source": "charjabug.gif",
    "speciesId": 737,
    "canonicalName": "charjabug",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "comfey.webp",
    "source": "comfey.gif",
    "speciesId": 764,
    "canonicalName": "comfey",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "cosmoem.webp",
    "source": "cosmoem.gif",
    "speciesId": 790,
    "canonicalName": "cosmoem",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "cosmog.webp",
    "source": "cosmog.gif",
    "speciesId": 789,
    "canonicalName": "cosmog",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "crabominable.webp",
    "source": "crabominable.gif",
    "speciesId": 740,
    "canonicalName": "crabominable",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "crabrawler.webp",
    "source": "crabrawler.gif",
    "speciesId": 739,
    "canonicalName": "crabrawler",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "cutiefly.webp",
    "source": "cutiefly.gif",
    "speciesId": 742,
    "canonicalName": "cutiefly",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "dartrix.webp",
    "source": "dartrix.gif",
    "speciesId": 723,
    "canonicalName": "dartrix",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "decidueye.webp",
    "source": "decidueye.gif",
    "speciesId": 724,
    "canonicalName": "decidueye",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "dewpider.webp",
    "source": "dewpider.gif",
    "speciesId": 751,
    "canonicalName": "dewpider",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "dhelmise.webp",
    "source": "dhelmise.gif",
    "speciesId": 781,
    "canonicalName": "dhelmise",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "diglett-alola.webp",
    "source": "diglett-alola.gif",
    "speciesId": 50,
    "canonicalName": "diglett-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "drampa.webp",
    "source": "drampa.gif",
    "speciesId": 780,
    "canonicalName": "drampa",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "dugtrio-alola.webp",
    "source": "dugtrio-alola.gif",
    "speciesId": 51,
    "canonicalName": "dugtrio-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "exeggutor-alola.webp",
    "source": "exeggutor-alola.gif",
    "speciesId": 103,
    "canonicalName": "exeggutor-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "fomantis.webp",
    "source": "fomantis.gif",
    "speciesId": 753,
    "canonicalName": "fomantis",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "geodude-alola.webp",
    "source": "geodude-alola.gif",
    "speciesId": 74,
    "canonicalName": "geodude-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "golem-alola.webp",
    "source": "golem-alola.gif",
    "speciesId": 76,
    "canonicalName": "golem-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "golisopod.webp",
    "source": "golisopod.gif",
    "speciesId": 768,
    "canonicalName": "golisopod",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "graveler-alola.webp",
    "source": "graveler-alola.gif",
    "speciesId": 75,
    "canonicalName": "graveler-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "grimer-alola.webp",
    "source": "grimer-alola.gif",
    "speciesId": 88,
    "canonicalName": "grimer-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "grubbin.webp",
    "source": "grubbin.gif",
    "speciesId": 736,
    "canonicalName": "grubbin",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "gumshoos.webp",
    "source": "gumshoos.gif",
    "speciesId": 735,
    "canonicalName": "gumshoos",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "guzzlord.webp",
    "source": "guzzlord.gif",
    "speciesId": 799,
    "canonicalName": "guzzlord",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "hakamo-o.webp",
    "source": "hakamo-o.gif",
    "speciesId": 783,
    "canonicalName": "hakamo-o",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "incineroar.webp",
    "source": "incineroar.gif",
    "speciesId": 727,
    "canonicalName": "incineroar",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "jangmo-o.webp",
    "source": "jangmo-o.gif",
    "speciesId": 782,
    "canonicalName": "jangmo-o",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "kartana.webp",
    "source": "kartana.gif",
    "speciesId": 798,
    "canonicalName": "kartana",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "komala.webp",
    "source": "komala.gif",
    "speciesId": 775,
    "canonicalName": "komala",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "kommo-o.webp",
    "source": "kommo-o.gif",
    "speciesId": 784,
    "canonicalName": "kommo-o",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "litten.webp",
    "source": "litten.gif",
    "speciesId": 725,
    "canonicalName": "litten",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "lunala.webp",
    "source": "lunala.gif",
    "speciesId": 792,
    "canonicalName": "lunala",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "lurantis.webp",
    "source": "lurantis.gif",
    "speciesId": 754,
    "canonicalName": "lurantis",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "lycanroc-dusk-usum.webp",
    "source": "Lycanroc-Dusk_usum.gif",
    "speciesId": 745,
    "canonicalName": "lycanroc-dusk",
    "games": [
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "lycanroc-midday.webp",
    "source": "lycanroc-Midday.gif",
    "speciesId": 745,
    "canonicalName": "lycanroc-midday",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "lycanroc-midnight.webp",
    "source": "lycanroc-midnight.gif",
    "speciesId": 745,
    "canonicalName": "lycanroc-midnight",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "magearna.webp",
    "source": "magearna.gif",
    "speciesId": 801,
    "canonicalName": "magearna",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "mareanie.webp",
    "source": "mareanie.gif",
    "speciesId": 747,
    "canonicalName": "mareanie",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "marowak-alola.webp",
    "source": "marowak-alola.gif",
    "speciesId": 105,
    "canonicalName": "marowak-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "marshadow.webp",
    "source": "marshadow.gif",
    "speciesId": 802,
    "canonicalName": "marshadow",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "meowth-alola.webp",
    "source": "meowth-alola.gif",
    "speciesId": 52,
    "canonicalName": "meowth-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "mimikyu-disguised.webp",
    "source": "mimikyu.gif",
    "speciesId": 778,
    "canonicalName": "mimikyu-disguised",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "minior-blue.webp",
    "source": "minior-blue.gif",
    "speciesId": 774,
    "canonicalName": "minior-blue",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "minior-green.webp",
    "source": "minior-green.gif",
    "speciesId": 774,
    "canonicalName": "minior-green",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "minior-indigo.webp",
    "source": "minior-indigo.gif",
    "speciesId": 774,
    "canonicalName": "minior-indigo",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "minior-orange.webp",
    "source": "minior-orange.gif",
    "speciesId": 774,
    "canonicalName": "minior-orange",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "minior-red.webp",
    "source": "minior-red.gif",
    "speciesId": 774,
    "canonicalName": "minior-red",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "minior-violet.webp",
    "source": "minior-violet.gif",
    "speciesId": 774,
    "canonicalName": "minior-violet",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "minior-yellow.webp",
    "source": "minior-yellow.gif",
    "speciesId": 774,
    "canonicalName": "minior-yellow",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "morelull.webp",
    "source": "morelull.gif",
    "speciesId": 755,
    "canonicalName": "morelull",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "mudbray.webp",
    "source": "mudbray.gif",
    "speciesId": 749,
    "canonicalName": "mudbray",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "mudsdale.webp",
    "source": "mudsdale.gif",
    "speciesId": 750,
    "canonicalName": "mudsdale",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "muk-alola.webp",
    "source": "muk-alola.gif",
    "speciesId": 89,
    "canonicalName": "muk-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "naganadel-usum.webp",
    "source": "Naganadel_usum.gif",
    "speciesId": 804,
    "canonicalName": "naganadel",
    "games": [
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "necrozma.webp",
    "source": "necrozma.gif",
    "speciesId": 800,
    "canonicalName": "necrozma",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "nihilego.webp",
    "source": "nihilego.gif",
    "speciesId": 793,
    "canonicalName": "nihilego",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "ninetales-alola.webp",
    "source": "ninetales-alola.gif",
    "speciesId": 38,
    "canonicalName": "ninetales-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "oranguru.webp",
    "source": "oranguru.gif",
    "speciesId": 765,
    "canonicalName": "oranguru",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "oricorio-baile.webp",
    "source": "oricorio-bayle.gif",
    "speciesId": 741,
    "canonicalName": "oricorio-baile",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "oricorio-pau.webp",
    "source": "oricorio-pau.gif",
    "speciesId": 741,
    "canonicalName": "oricorio-pau",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "oricorio-pom-pom.webp",
    "source": "oricorio-PomPom.gif",
    "speciesId": 741,
    "canonicalName": "oricorio-pom-pom",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "oricorio-sensu.webp",
    "source": "oricorio-sensu.gif",
    "speciesId": 741,
    "canonicalName": "oricorio-sensu",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "palossand.webp",
    "source": "palossand.gif",
    "speciesId": 770,
    "canonicalName": "palossand",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "passimian.webp",
    "source": "passimian.gif",
    "speciesId": 766,
    "canonicalName": "passimian",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "persian-alola.webp",
    "source": "persian-alola.gif",
    "speciesId": 53,
    "canonicalName": "persian-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "pheromosa.webp",
    "source": "pheromosa.gif",
    "speciesId": 795,
    "canonicalName": "pheromosa",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "pikachu-partner-cap-usum.webp",
    "source": "pikachu-PartnerCap_usum.gif",
    "speciesId": 25,
    "canonicalName": "pikachu-partner-cap",
    "games": [
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "pikipek.webp",
    "source": "pikipek.gif",
    "speciesId": 731,
    "canonicalName": "pikipek",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "poipole-usum.webp",
    "source": "Poipole_usum.gif",
    "speciesId": 803,
    "canonicalName": "poipole",
    "games": [
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "popplio.webp",
    "source": "popplio.gif",
    "speciesId": 728,
    "canonicalName": "popplio",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "primarina.webp",
    "source": "primarina.gif",
    "speciesId": 730,
    "canonicalName": "primarina",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "pyukumuku.webp",
    "source": "pyukumuku.gif",
    "speciesId": 771,
    "canonicalName": "pyukumuku",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "raichu-alola.webp",
    "source": "raichu-alola.gif",
    "speciesId": 26,
    "canonicalName": "raichu-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "raticate-alola.webp",
    "source": "raticate-alola.gif",
    "speciesId": 20,
    "canonicalName": "raticate-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "rattata-alola.webp",
    "source": "rattata-alola.gif",
    "speciesId": 19,
    "canonicalName": "rattata-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "ribombee.webp",
    "source": "ribombee.gif",
    "speciesId": 743,
    "canonicalName": "ribombee",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "rockruff.webp",
    "source": "rockruff.gif",
    "speciesId": 744,
    "canonicalName": "rockruff",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "rowlet.webp",
    "source": "rowlet.gif",
    "speciesId": 722,
    "canonicalName": "rowlet",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "salandit.webp",
    "source": "salandit.gif",
    "speciesId": 757,
    "canonicalName": "salandit",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "salazzle.webp",
    "source": "salazzle.gif",
    "speciesId": 758,
    "canonicalName": "salazzle",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "sandshrew-alola.webp",
    "source": "sandshrew-alola.gif",
    "speciesId": 27,
    "canonicalName": "sandshrew-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "sandslash-alola.webp",
    "source": "sandslash-alola.gif",
    "speciesId": 28,
    "canonicalName": "sandslash-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "sandygast.webp",
    "source": "sandygast.gif",
    "speciesId": 769,
    "canonicalName": "sandygast",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "shiinotic.webp",
    "source": "shiinotic.gif",
    "speciesId": 756,
    "canonicalName": "shiinotic",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-bug.webp",
    "source": "silvally-bug.gif",
    "speciesId": 773,
    "canonicalName": "silvally-bug",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-dark.webp",
    "source": "silvally-dark.gif",
    "speciesId": 773,
    "canonicalName": "silvally-dark",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-dragon.webp",
    "source": "silvally-dragon.gif",
    "speciesId": 773,
    "canonicalName": "silvally-dragon",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-electric.webp",
    "source": "silvally-electric.gif",
    "speciesId": 773,
    "canonicalName": "silvally-electric",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-fairy.webp",
    "source": "silvally-fairy.gif",
    "speciesId": 773,
    "canonicalName": "silvally-fairy",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-fighting.webp",
    "source": "silvally-fighting.gif",
    "speciesId": 773,
    "canonicalName": "silvally-fighting",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-fire.webp",
    "source": "silvally-fire.gif",
    "speciesId": 773,
    "canonicalName": "silvally-fire",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-flying.webp",
    "source": "silvally-flying.gif",
    "speciesId": 773,
    "canonicalName": "silvally-flying",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-ghost.webp",
    "source": "silvally-ghost.gif",
    "speciesId": 773,
    "canonicalName": "silvally-ghost",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-grass.webp",
    "source": "silvally-grass.gif",
    "speciesId": 773,
    "canonicalName": "silvally-grass",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-ground.webp",
    "source": "silvally-ground.gif",
    "speciesId": 773,
    "canonicalName": "silvally-ground",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-ice.webp",
    "source": "silvally-ice.gif",
    "speciesId": 773,
    "canonicalName": "silvally-ice",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-poison.webp",
    "source": "silvally-poison.gif",
    "speciesId": 773,
    "canonicalName": "silvally-poison",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-psychic.webp",
    "source": "silvally-psychic.gif",
    "speciesId": 773,
    "canonicalName": "silvally-psychic",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-rock.webp",
    "source": "silvally-rock.gif",
    "speciesId": 773,
    "canonicalName": "silvally-rock",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-steel.webp",
    "source": "silvally-steel.gif",
    "speciesId": 773,
    "canonicalName": "silvally-steel",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally-water.webp",
    "source": "silvally-water.gif",
    "speciesId": 773,
    "canonicalName": "silvally-water",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "silvally.webp",
    "source": "silvally.gif",
    "speciesId": 773,
    "canonicalName": "silvally",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "solgaleo.webp",
    "source": "solgaleo.gif",
    "speciesId": 791,
    "canonicalName": "solgaleo",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "stakataka-usum.webp",
    "source": "Stakataka_usum.gif",
    "speciesId": 805,
    "canonicalName": "stakataka",
    "games": [
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "steenee.webp",
    "source": "steenee.gif",
    "speciesId": 762,
    "canonicalName": "steenee",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "stufful.webp",
    "source": "stufful.gif",
    "speciesId": 759,
    "canonicalName": "stufful",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "tapu-bulu.webp",
    "source": "tapubulu.gif",
    "speciesId": 787,
    "canonicalName": "tapu-bulu",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "tapu-fini.webp",
    "source": "tapufini.gif",
    "speciesId": 788,
    "canonicalName": "tapu-fini",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "tapu-koko.webp",
    "source": "tapukoko.gif",
    "speciesId": 785,
    "canonicalName": "tapu-koko",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "tapu-lele.webp",
    "source": "tapulele.gif",
    "speciesId": 786,
    "canonicalName": "tapu-lele",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "togedemaru.webp",
    "source": "togedemaru.gif",
    "speciesId": 777,
    "canonicalName": "togedemaru",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "torracat.webp",
    "source": "torracat.gif",
    "speciesId": 726,
    "canonicalName": "torracat",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "toucannon.webp",
    "source": "toucannon.gif",
    "speciesId": 733,
    "canonicalName": "toucannon",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "toxapex.webp",
    "source": "toxapex.gif",
    "speciesId": 748,
    "canonicalName": "toxapex",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "trumbeak.webp",
    "source": "trumbeak.gif",
    "speciesId": 732,
    "canonicalName": "trumbeak",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "tsareena.webp",
    "source": "tsareena.gif",
    "speciesId": 763,
    "canonicalName": "tsareena",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "turtonator.webp",
    "source": "turtonator.gif",
    "speciesId": 776,
    "canonicalName": "turtonator",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "type-null.webp",
    "source": "typenull.gif",
    "speciesId": 772,
    "canonicalName": "type-null",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "vikavolt.webp",
    "source": "vikavolt.gif",
    "speciesId": 738,
    "canonicalName": "vikavolt",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "vulpix-alola.webp",
    "source": "vulpix-alola.gif",
    "speciesId": 37,
    "canonicalName": "vulpix-alola",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "wimpod.webp",
    "source": "wimpod.gif",
    "speciesId": 767,
    "canonicalName": "wimpod",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "wishiwashi.webp",
    "source": "wishiwashi.gif",
    "speciesId": 746,
    "canonicalName": "wishiwashi",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "xurkitree.webp",
    "source": "xurkitree.gif",
    "speciesId": 796,
    "canonicalName": "xurkitree",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "yungoos.webp",
    "source": "yungoos.gif",
    "speciesId": 734,
    "canonicalName": "yungoos",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "zeraora-usum.webp",
    "source": "Zeraora_usum.gif",
    "speciesId": 807,
    "canonicalName": "zeraora",
    "games": [
      "ultrasun",
      "ultramoon"
    ]
  },
  {
    "file": "zygarde-10.webp",
    "source": "zygarde-10.gif",
    "speciesId": 718,
    "canonicalName": "zygarde-10",
    "games": [
      "sun",
      "moon",
      "ultrasun",
      "ultramoon"
    ]
  }
] as const;
