// Generated by scripts/generate-swsh-shiny-model-manifest.mjs. Do not edit by hand.
// Source: Category:Sword and Shield Shiny models, Bulbagarden Archives.
//
// This checked-in bootstrap preserves the previously verified Archive files.
// Run the generator with network access to replace it with the complete category
// snapshot; it fails and writes a report if an Archive file is not mapped.
export const SWORD_SHIELD_SHINY_MODEL_ENTRIES = [
  { filename: 'Spr_8s_001_s.png', speciesId: 1, suffix: '', gender: null, canonicalName: 'bulbasaur' },
  { filename: 'Spr_8s_003_s.png', speciesId: 3, suffix: '', gender: null, canonicalName: 'venusaur' },
  { filename: 'Spr_8s_003_f_s.png', speciesId: 3, suffix: '', gender: 'female', canonicalName: 'venusaur' },
  { filename: 'Spr_8s_052-G_s.png', speciesId: 52, suffix: 'G', gender: null, canonicalName: 'meowth-galar' },
  { filename: 'Spr_8s_078-G_s.png', speciesId: 78, suffix: 'G', gender: null, canonicalName: 'rapidash-galar' },
  { filename: 'Spr_8s_445_s.png', speciesId: 445, suffix: '', gender: null, canonicalName: 'garchomp' },
  { filename: 'Spr_8s_445_f_s.png', speciesId: 445, suffix: '', gender: 'female', canonicalName: 'garchomp' },
  { filename: 'Spr_8s_810_s.png', speciesId: 810, suffix: '', gender: null, canonicalName: 'grookey' },
] as const;
